/*
Deployment script for BEK_Commerce_AppData

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar BEK_Commerce_profiles "BEK_Commerce_profiles"
:setvar BEK_Commerce_transactions "BEK_Commerce_transactions"
:setvar DatabaseName "BEK_Commerce_AppData"
:setvar DefaultFilePrefix "BEK_Commerce_AppData"
:setvar DefaultDataPath "J:\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "P:\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key b3db364a-c43f-46bd-a840-f7b8f6436a62 is skipped, element [dbo].[AppSettings].[Id] (SqlSimpleColumn) will not be renamed to Key';


GO
PRINT N'Rename refactoring operation with key ab46afd1-6f2d-4305-82cd-126cdf2cb973 is skipped, element [dbo].[AppSettings].[Setting] (SqlSimpleColumn) will not be renamed to Value';


GO
PRINT N'Altering [ETL].[Staging_FSE_ProductAllergens]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER TABLE [ETL].[Staging_FSE_ProductAllergens] ALTER COLUMN [AllergenTypeCode] VARCHAR (10) NULL;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Altering [Orders].[OrderHistoryHeader]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
ALTER TABLE [Orders].[OrderHistoryHeader]
    ADD [OrderSubtotal] DECIMAL (18, 2) DEFAULT ((0)) NOT NULL;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [Configuration].[AppSettings]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE TABLE [Configuration].[AppSettings] (
    [Key]      VARCHAR (50)  NOT NULL,
    [Value]    VARCHAR (MAX) NOT NULL,
    [Comment]  VARCHAR (MAX) NOT NULL,
    [Disabled] BIT           NOT NULL,
    PRIMARY KEY CLUSTERED ([Key] ASC)
);


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [Configuration].[AppSettings].[IX_AppSettings_Key]...';


GO
CREATE NONCLUSTERED INDEX [IX_AppSettings_Key]
    ON [Configuration].[AppSettings]([Key] ASC);


GO
PRINT N'Creating [Customers].[InternalUserAccess]...';


GO
CREATE TABLE [Customers].[InternalUserAccess] (
    [Id]             BIGINT           IDENTITY (1, 1) NOT NULL,
    [BranchId]       CHAR (3)         NOT NULL,
    [CustomerNumber] CHAR (6)         NULL,
    [UserId]         UNIQUEIDENTIFIER NOT NULL,
    [CustomerId]     UNIQUEIDENTIFIER NOT NULL,
    [RoleId]         VARCHAR (70)     NOT NULL,
    [EmailAddress]   VARCHAR (200)    NOT NULL,
    [CreatedUtc]     DATETIME         NOT NULL,
    [ModifiedUtc]    DATETIME         NOT NULL,
    CONSTRAINT [PK_Customers.InternalUserAccess] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating unnamed constraint on [Configuration].[AppSettings]...';


GO
ALTER TABLE [Configuration].[AppSettings]
    ADD DEFAULT 0 FOR [Disabled];


GO
PRINT N'Creating unnamed constraint on [Customers].[InternalUserAccess]...';


GO
ALTER TABLE [Customers].[InternalUserAccess]
    ADD DEFAULT (getutcdate()) FOR [CreatedUtc];


GO
PRINT N'Creating unnamed constraint on [Customers].[InternalUserAccess]...';


GO
ALTER TABLE [Customers].[InternalUserAccess]
    ADD DEFAULT (getutcdate()) FOR [ModifiedUtc];


GO
PRINT N'Altering [ETL].[ProcessBEKItemNumbersForUNFIByVendorId]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
/*
* Retieve BEK ItemNumber by VendorId using External Catalogs for branch
* 
* Author: mdjoiner
* Changed: 2016-05-13
*/
ALTER PROCEDURE [ETL].[ProcessBEKItemNumbersForUNFIByVendorId]
    @vendorId varchar(10)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE
        unfi
    SET
        unfi.ProductNumber = item.ItemId,
        unfi.StockedInBranches = ETL.ConcatBranchesForItem(@vendorId, item.ItemId)
    FROM
        ETL.Staging_UNFIProducts unfi
        JOIN ETL.Staging_ItemData item ON item.MfrNumber = unfi.ProductNumber
    WHERE
        item.Vendor1 = @vendorId
    AND
        item.SpecialOrderItem = 'N'
END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [Configuration].[CheckAppSettingsForChange]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
 CREATE PROCEDURE [Configuration].[CheckAppSettingsForChange]
 AS
 BEGIN
 SET NOCOUNT ON;
   SELECT 
     Value
   FROM 
     [Configuration].[AppSettings]
   WHERE
       [Key] = 'DBChangeValue'
 END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [Configuration].[GetAppSetting]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE PROCEDURE [Configuration].[GetAppSetting]
	@Key		varchar(50)
AS
	SELECT 
 		[Key], 
		Value,
		Comment,
		[Disabled]
 	FROM 
 		[Configuration].[AppSettings]
 	WHERE
 	    [Key] = @Key
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [Configuration].[ReadAppSettings]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
 CREATE PROCEDURE [Configuration].[ReadAppSettings]
 AS
 BEGIN
 SET NOCOUNT ON;
 	SELECT 
 		[Key], 
		Value,
		Comment,
		[Disabled]
 	FROM 
 		[Configuration].[AppSettings]
 	WHERE
 	    [Disabled] = 0
 END
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [Configuration].[SaveAppSetting]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
CREATE PROCEDURE [Configuration].[SaveAppSetting]
	@Key		VARCHAR(50),
	@Value		VARCHAR(MAX),
	@Comment	VARCHAR(MAX),
	@Disabled	BIT
AS
	UPDATE	Configuration.AppSettings
	SET
		[Value] = @Value,
		[Comment] = @Comment,
		[Disabled] = @Disabled
	WHERE
		[Key] = @Key
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating [ETL].[ReadAverageItemUsage]...';


GO

CREATE PROCEDURE [ETL].[ReadAverageItemUsage]	
	@NumDays int
AS

--NEED TO ADD SUMMARY COMMENTS HERE

SET NOCOUNT ON;

SELECT
	oh.BranchId
	, oh.CustomerNumber
	, od.ItemNumber
	, od.unitOfMeasure
	, AVG(od.ShippedQuantity) 'AverageUse'
FROM 
	Orders.OrderHistoryHeader oh
		INNER JOIN Orders.OrderHistoryDetail od ON od.OrderHistoryHeader_Id = oh.Id
WHERE 
	oh.CreatedUtc > DATEADD(DD, (@NumDays * -1), GETDATE())
GROUP BY 
	oh.BranchId
	, oh.CustomerNumber
	, od.ItemNumber
	, od.unitOfMeasure
GO
PRINT N'Refreshing [ETL].[ReadItemGS1Data]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[ETL].[ReadItemGS1Data]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [ETL].[ProcessItemHistoryData]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[ETL].[ProcessItemHistoryData]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Refreshing [ETL].[PurgeOrderHistory_AppData]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
EXECUTE sp_refreshsqlmodule N'[ETL].[PurgeOrderHistory_AppData]';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'b3db364a-c43f-46bd-a840-f7b8f6436a62')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('b3db364a-c43f-46bd-a840-f7b8f6436a62')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ab46afd1-6f2d-4305-82cd-126cdf2cb973')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ab46afd1-6f2d-4305-82cd-126cdf2cb973')

GO

GO
PRINT N'Update complete.';


GO
