CREATE DATABASE [SSISSupport_ECOM]
GO

ALTER DATABASE [SSISSupport_ECOM] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [SSISSupport_ECOM].[dbo].[sp_fulltext_database] @action = 'enable'
END 
GO

ALTER DATABASE [SSISSupport_ECOM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET ARITHABORT OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [SSISSupport_ECOM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SSISSupport_ECOM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SSISSupport_ECOM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SSISSupport_ECOM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SSISSupport_ECOM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET RECOVERY FULL 
GO
ALTER DATABASE [SSISSupport_ECOM] SET  MULTI_USER 
GO
ALTER DATABASE [SSISSupport_ECOM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SSISSupport_ECOM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SSISSupport_ECOM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SSISSupport_ECOM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SSISSupport_ECOM', N'ON'
GO