//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.MessagingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.MessagingService.IMessagingService")]
    public interface IMessagingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/CreateMailMessage", ReplyAction="http://tempuri.org/IMessagingService/CreateMailMessageResponse")]
        void CreateMailMessage(KeithLink.Svc.Core.Models.Messaging.MailMessageModel mailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/CreateMailMessage", ReplyAction="http://tempuri.org/IMessagingService/CreateMailMessageResponse")]
        System.Threading.Tasks.Task CreateMailMessageAsync(KeithLink.Svc.Core.Models.Messaging.MailMessageModel mailMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/CreateUserMessage", ReplyAction="http://tempuri.org/IMessagingService/CreateUserMessageResponse")]
        long CreateUserMessage(System.Guid userId, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, KeithLink.Svc.Core.Models.Messaging.UserMessageModel userMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/CreateUserMessage", ReplyAction="http://tempuri.org/IMessagingService/CreateUserMessageResponse")]
        System.Threading.Tasks.Task<long> CreateUserMessageAsync(System.Guid userId, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, KeithLink.Svc.Core.Models.Messaging.UserMessageModel userMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/GetUnreadMessagesCount", ReplyAction="http://tempuri.org/IMessagingService/GetUnreadMessagesCountResponse")]
        int GetUnreadMessagesCount(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/GetUnreadMessagesCount", ReplyAction="http://tempuri.org/IMessagingService/GetUnreadMessagesCountResponse")]
        System.Threading.Tasks.Task<int> GetUnreadMessagesCountAsync(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/MarkAsReadUserMessages", ReplyAction="http://tempuri.org/IMessagingService/MarkAsReadUserMessagesResponse")]
        void MarkAsReadUserMessages(KeithLink.Svc.Core.Models.Messaging.UserMessageModel[] userMessages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/MarkAsReadUserMessages", ReplyAction="http://tempuri.org/IMessagingService/MarkAsReadUserMessagesResponse")]
        System.Threading.Tasks.Task MarkAsReadUserMessagesAsync(KeithLink.Svc.Core.Models.Messaging.UserMessageModel[] userMessages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/MarkAllReadByUser", ReplyAction="http://tempuri.org/IMessagingService/MarkAllReadByUserResponse")]
        void MarkAllReadByUser(KeithLink.Svc.Core.Models.Profile.UserProfile user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/MarkAllReadByUser", ReplyAction="http://tempuri.org/IMessagingService/MarkAllReadByUserResponse")]
        System.Threading.Tasks.Task MarkAllReadByUserAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadMessagingPreferences", ReplyAction="http://tempuri.org/IMessagingService/ReadMessagingPreferencesResponse")]
        KeithLink.Svc.Core.Models.Messaging.UserMessagingPreferenceModel[] ReadMessagingPreferences(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadMessagingPreferences", ReplyAction="http://tempuri.org/IMessagingService/ReadMessagingPreferencesResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Messaging.UserMessagingPreferenceModel[]> ReadMessagingPreferencesAsync(System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadMessageTemplateForKey", ReplyAction="http://tempuri.org/IMessagingService/ReadMessageTemplateForKeyResponse")]
        KeithLink.Svc.Core.Models.Configuration.MessageTemplateModel ReadMessageTemplateForKey(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadMessageTemplateForKey", ReplyAction="http://tempuri.org/IMessagingService/ReadMessageTemplateForKeyResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Configuration.MessageTemplateModel> ReadMessageTemplateForKeyAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadPagedUserMessages", ReplyAction="http://tempuri.org/IMessagingService/ReadPagedUserMessagesResponse")]
        KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.Messaging.UserMessageModel> ReadPagedUserMessages(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadPagedUserMessages", ReplyAction="http://tempuri.org/IMessagingService/ReadPagedUserMessagesResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.Messaging.UserMessageModel>> ReadPagedUserMessagesAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadUserMessages", ReplyAction="http://tempuri.org/IMessagingService/ReadUserMessagesResponse")]
        KeithLink.Svc.Core.Models.Messaging.UserMessageModel[] ReadUserMessages(KeithLink.Svc.Core.Models.Profile.UserProfile user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/ReadUserMessages", ReplyAction="http://tempuri.org/IMessagingService/ReadUserMessagesResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Messaging.UserMessageModel[]> ReadUserMessagesAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/RegisterPushDevice", ReplyAction="http://tempuri.org/IMessagingService/RegisterPushDeviceResponse")]
        bool RegisterPushDevice(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Messaging.PushDeviceRegistrationModel deviceRegistrationModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/RegisterPushDevice", ReplyAction="http://tempuri.org/IMessagingService/RegisterPushDeviceResponse")]
        System.Threading.Tasks.Task<bool> RegisterPushDeviceAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Messaging.PushDeviceRegistrationModel deviceRegistrationModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/UpdateMessagingPreferences", ReplyAction="http://tempuri.org/IMessagingService/UpdateMessagingPreferencesResponse")]
        void UpdateMessagingPreferences(KeithLink.Svc.Core.Models.Messaging.ProfileMessagingPreferenceModel messagingPreferenceModel, KeithLink.Svc.Core.Models.Profile.UserProfile user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagingService/UpdateMessagingPreferences", ReplyAction="http://tempuri.org/IMessagingService/UpdateMessagingPreferencesResponse")]
        System.Threading.Tasks.Task UpdateMessagingPreferencesAsync(KeithLink.Svc.Core.Models.Messaging.ProfileMessagingPreferenceModel messagingPreferenceModel, KeithLink.Svc.Core.Models.Profile.UserProfile user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagingServiceChannel : KeithLink.Svc.WebApi.com.benekeith.MessagingService.IMessagingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.MessagingService.IMessagingService>, KeithLink.Svc.WebApi.com.benekeith.MessagingService.IMessagingService {
        
        public MessagingServiceClient() {
        }
        
        public MessagingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateMailMessage(KeithLink.Svc.Core.Models.Messaging.MailMessageModel mailMessage) {
            base.Channel.CreateMailMessage(mailMessage);
        }
        
        public System.Threading.Tasks.Task CreateMailMessageAsync(KeithLink.Svc.Core.Models.Messaging.MailMessageModel mailMessage) {
            return base.Channel.CreateMailMessageAsync(mailMessage);
        }
        
        public long CreateUserMessage(System.Guid userId, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, KeithLink.Svc.Core.Models.Messaging.UserMessageModel userMessage) {
            return base.Channel.CreateUserMessage(userId, catalogInfo, userMessage);
        }
        
        public System.Threading.Tasks.Task<long> CreateUserMessageAsync(System.Guid userId, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, KeithLink.Svc.Core.Models.Messaging.UserMessageModel userMessage) {
            return base.Channel.CreateUserMessageAsync(userId, catalogInfo, userMessage);
        }
        
        public int GetUnreadMessagesCount(System.Guid userId) {
            return base.Channel.GetUnreadMessagesCount(userId);
        }
        
        public System.Threading.Tasks.Task<int> GetUnreadMessagesCountAsync(System.Guid userId) {
            return base.Channel.GetUnreadMessagesCountAsync(userId);
        }
        
        public void MarkAsReadUserMessages(KeithLink.Svc.Core.Models.Messaging.UserMessageModel[] userMessages) {
            base.Channel.MarkAsReadUserMessages(userMessages);
        }
        
        public System.Threading.Tasks.Task MarkAsReadUserMessagesAsync(KeithLink.Svc.Core.Models.Messaging.UserMessageModel[] userMessages) {
            return base.Channel.MarkAsReadUserMessagesAsync(userMessages);
        }
        
        public void MarkAllReadByUser(KeithLink.Svc.Core.Models.Profile.UserProfile user) {
            base.Channel.MarkAllReadByUser(user);
        }
        
        public System.Threading.Tasks.Task MarkAllReadByUserAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user) {
            return base.Channel.MarkAllReadByUserAsync(user);
        }
        
        public KeithLink.Svc.Core.Models.Messaging.UserMessagingPreferenceModel[] ReadMessagingPreferences(System.Guid userId) {
            return base.Channel.ReadMessagingPreferences(userId);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Messaging.UserMessagingPreferenceModel[]> ReadMessagingPreferencesAsync(System.Guid userId) {
            return base.Channel.ReadMessagingPreferencesAsync(userId);
        }
        
        public KeithLink.Svc.Core.Models.Configuration.MessageTemplateModel ReadMessageTemplateForKey(string key) {
            return base.Channel.ReadMessageTemplateForKey(key);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Configuration.MessageTemplateModel> ReadMessageTemplateForKeyAsync(string key) {
            return base.Channel.ReadMessageTemplateForKeyAsync(key);
        }
        
        public KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.Messaging.UserMessageModel> ReadPagedUserMessages(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging) {
            return base.Channel.ReadPagedUserMessages(user, paging);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.Messaging.UserMessageModel>> ReadPagedUserMessagesAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging) {
            return base.Channel.ReadPagedUserMessagesAsync(user, paging);
        }
        
        public KeithLink.Svc.Core.Models.Messaging.UserMessageModel[] ReadUserMessages(KeithLink.Svc.Core.Models.Profile.UserProfile user) {
            return base.Channel.ReadUserMessages(user);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Messaging.UserMessageModel[]> ReadUserMessagesAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user) {
            return base.Channel.ReadUserMessagesAsync(user);
        }
        
        public bool RegisterPushDevice(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Messaging.PushDeviceRegistrationModel deviceRegistrationModel) {
            return base.Channel.RegisterPushDevice(user, deviceRegistrationModel);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterPushDeviceAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Messaging.PushDeviceRegistrationModel deviceRegistrationModel) {
            return base.Channel.RegisterPushDeviceAsync(user, deviceRegistrationModel);
        }
        
        public void UpdateMessagingPreferences(KeithLink.Svc.Core.Models.Messaging.ProfileMessagingPreferenceModel messagingPreferenceModel, KeithLink.Svc.Core.Models.Profile.UserProfile user) {
            base.Channel.UpdateMessagingPreferences(messagingPreferenceModel, user);
        }
        
        public System.Threading.Tasks.Task UpdateMessagingPreferencesAsync(KeithLink.Svc.Core.Models.Messaging.ProfileMessagingPreferenceModel messagingPreferenceModel, KeithLink.Svc.Core.Models.Profile.UserProfile user) {
            return base.Channel.UpdateMessagingPreferencesAsync(messagingPreferenceModel, user);
        }
    }
}
