//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.OnlinePaymentService.IOnlinePaymentService")]
    public interface IOnlinePaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/DeleteInvoice", ReplyAction="http://tempuri.org/IOnlinePaymentService/DeleteInvoiceResponse")]
        void DeleteInvoice(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/DeleteInvoice", ReplyAction="http://tempuri.org/IOnlinePaymentService/DeleteInvoiceResponse")]
        System.Threading.Tasks.Task DeleteInvoiceAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetAllBankAccounts", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetAllBankAccountsResponse")]
        KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[] GetAllBankAccounts(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetAllBankAccounts", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetAllBankAccountsResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[]> GetAllBankAccountsAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetBankAccount", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetBankAccountResponse")]
        KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank GetBankAccount(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetBankAccount", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetBankAccountResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank> GetBankAccountAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetInvoiceHeaders", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetInvoiceHeadersResponse")]
        KeithLink.Svc.Core.Models.Invoices.InvoiceHeaderReturnModel GetInvoiceHeaders(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, KeithLink.Svc.Core.Models.Paging.PagingModel paging, bool forAllCustomers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetInvoiceHeaders", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetInvoiceHeadersResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceHeaderReturnModel> GetInvoiceHeadersAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, KeithLink.Svc.Core.Models.Paging.PagingModel paging, bool forAllCustomers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/MakeInvoicePayment", ReplyAction="http://tempuri.org/IOnlinePaymentService/MakeInvoicePaymentResponse")]
        void MakeInvoicePayment(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string emailAddress, KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel[] payments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/MakeInvoicePayment", ReplyAction="http://tempuri.org/IOnlinePaymentService/MakeInvoicePaymentResponse")]
        System.Threading.Tasks.Task MakeInvoicePaymentAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string emailAddress, KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel[] payments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetInvoiceDetails", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetInvoiceDetailsResponse")]
        KeithLink.Svc.Core.Models.Invoices.InvoiceModel GetInvoiceDetails(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetInvoiceDetails", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetInvoiceDetailsResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceModel> GetInvoiceDetailsAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/PendingTransactionsAllCustomers", ReplyAction="http://tempuri.org/IOnlinePaymentService/PendingTransactionsAllCustomersResponse")]
        KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel> PendingTransactionsAllCustomers(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/PendingTransactionsAllCustomers", ReplyAction="http://tempuri.org/IOnlinePaymentService/PendingTransactionsAllCustomersResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel>> PendingTransactionsAllCustomersAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetCustomerAccountBalance", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetCustomerAccountBalanceResponse")]
        KeithLink.Svc.Core.Models.Profile.CustomerAccountBalanceModel GetCustomerAccountBalance(string customerId, string branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetCustomerAccountBalance", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetCustomerAccountBalanceResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Profile.CustomerAccountBalanceModel> GetCustomerAccountBalanceAsync(string customerId, string branchId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlinePaymentServiceChannel : KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService.IOnlinePaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlinePaymentServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService.IOnlinePaymentService>, KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService.IOnlinePaymentService {
        
        public OnlinePaymentServiceClient() {
        }
        
        public OnlinePaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlinePaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteInvoice(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber) {
            base.Channel.DeleteInvoice(userContext, invoiceNumber);
        }
        
        public System.Threading.Tasks.Task DeleteInvoiceAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber) {
            return base.Channel.DeleteInvoiceAsync(userContext, invoiceNumber);
        }
        
        public KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[] GetAllBankAccounts(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext) {
            return base.Channel.GetAllBankAccounts(userContext);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[]> GetAllBankAccountsAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext) {
            return base.Channel.GetAllBankAccountsAsync(userContext);
        }
        
        public KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank GetBankAccount(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber) {
            return base.Channel.GetBankAccount(userContext, accountNumber);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank> GetBankAccountAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber) {
            return base.Channel.GetBankAccountAsync(userContext, accountNumber);
        }
        
        public KeithLink.Svc.Core.Models.Invoices.InvoiceHeaderReturnModel GetInvoiceHeaders(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, KeithLink.Svc.Core.Models.Paging.PagingModel paging, bool forAllCustomers) {
            return base.Channel.GetInvoiceHeaders(user, userContext, paging, forAllCustomers);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceHeaderReturnModel> GetInvoiceHeadersAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, KeithLink.Svc.Core.Models.Paging.PagingModel paging, bool forAllCustomers) {
            return base.Channel.GetInvoiceHeadersAsync(user, userContext, paging, forAllCustomers);
        }
        
        public void MakeInvoicePayment(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string emailAddress, KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel[] payments) {
            base.Channel.MakeInvoicePayment(userContext, emailAddress, payments);
        }
        
        public System.Threading.Tasks.Task MakeInvoicePaymentAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string emailAddress, KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel[] payments) {
            return base.Channel.MakeInvoicePaymentAsync(userContext, emailAddress, payments);
        }
        
        public KeithLink.Svc.Core.Models.Invoices.InvoiceModel GetInvoiceDetails(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber) {
            return base.Channel.GetInvoiceDetails(userContext, invoiceNumber);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceModel> GetInvoiceDetailsAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string invoiceNumber) {
            return base.Channel.GetInvoiceDetailsAsync(userContext, invoiceNumber);
        }
        
        public KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel> PendingTransactionsAllCustomers(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging) {
            return base.Channel.PendingTransactionsAllCustomers(user, paging);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Paging.PagedResults<KeithLink.Svc.Core.Models.OnlinePayments.Payment.PaymentTransactionModel>> PendingTransactionsAllCustomersAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.Paging.PagingModel paging) {
            return base.Channel.PendingTransactionsAllCustomersAsync(user, paging);
        }
        
        public KeithLink.Svc.Core.Models.Profile.CustomerAccountBalanceModel GetCustomerAccountBalance(string customerId, string branchId) {
            return base.Channel.GetCustomerAccountBalance(customerId, branchId);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Profile.CustomerAccountBalanceModel> GetCustomerAccountBalanceAsync(string customerId, string branchId) {
            return base.Channel.GetCustomerAccountBalanceAsync(customerId, branchId);
        }
    }
}
