//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.OnlinePaymentService.IOnlinePaymentService")]
    public interface IOnlinePaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetAllBankAccounts", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetAllBankAccountsResponse")]
        KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[] GetAllBankAccounts(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetAllBankAccounts", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetAllBankAccountsResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[]> GetAllBankAccountsAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetBankAccount", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetBankAccountResponse")]
        KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank GetBankAccount(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlinePaymentService/GetBankAccount", ReplyAction="http://tempuri.org/IOnlinePaymentService/GetBankAccountResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank> GetBankAccountAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOnlinePaymentServiceChannel : KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService.IOnlinePaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlinePaymentServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService.IOnlinePaymentService>, KeithLink.Svc.WebApi.com.benekeith.OnlinePaymentService.IOnlinePaymentService {
        
        public OnlinePaymentServiceClient() {
        }
        
        public OnlinePaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlinePaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[] GetAllBankAccounts(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext) {
            return base.Channel.GetAllBankAccounts(userContext);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank[]> GetAllBankAccountsAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext) {
            return base.Channel.GetAllBankAccountsAsync(userContext);
        }
        
        public KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank GetBankAccount(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber) {
            return base.Channel.GetBankAccount(userContext, accountNumber);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.OnlinePayments.Customer.CustomerBank> GetBankAccountAsync(KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext userContext, string accountNumber) {
            return base.Channel.GetBankAccountAsync(userContext, accountNumber);
        }
    }
}
