//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Ext.Pipeline.ItemPrice.PipelineService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class product : KeithLink.Ext.Pipeline.ItemPrice.PipelineService.BaseProductInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string casesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categorynameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cubeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ext_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kosherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manufacturer_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string manufacturer_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KeithLink.Ext.Pipeline.ItemPrice.PipelineService.nutritional nutritionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string packField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KeithLink.Ext.Pipeline.ItemPrice.PipelineService.ProductImage[] productimagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string temp_zoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string upcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_numField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cases {
            get {
                return this.casesField;
            }
            set {
                if ((object.ReferenceEquals(this.casesField, value) != true)) {
                    this.casesField = value;
                    this.RaisePropertyChanged("cases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryIdField, value) != true)) {
                    this.categoryIdField = value;
                    this.RaisePropertyChanged("categoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoryname {
            get {
                return this.categorynameField;
            }
            set {
                if ((object.ReferenceEquals(this.categorynameField, value) != true)) {
                    this.categorynameField = value;
                    this.RaisePropertyChanged("categoryname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                if ((object.ReferenceEquals(this.classField, value) != true)) {
                    this.classField = value;
                    this.RaisePropertyChanged("class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cube {
            get {
                return this.cubeField;
            }
            set {
                if ((object.ReferenceEquals(this.cubeField, value) != true)) {
                    this.cubeField = value;
                    this.RaisePropertyChanged("cube");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ext_description {
            get {
                return this.ext_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ext_descriptionField, value) != true)) {
                    this.ext_descriptionField = value;
                    this.RaisePropertyChanged("ext_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kosher {
            get {
                return this.kosherField;
            }
            set {
                if ((object.ReferenceEquals(this.kosherField, value) != true)) {
                    this.kosherField = value;
                    this.RaisePropertyChanged("kosher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string manufacturer_name {
            get {
                return this.manufacturer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.manufacturer_nameField, value) != true)) {
                    this.manufacturer_nameField = value;
                    this.RaisePropertyChanged("manufacturer_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string manufacturer_number {
            get {
                return this.manufacturer_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.manufacturer_numberField, value) != true)) {
                    this.manufacturer_numberField = value;
                    this.RaisePropertyChanged("manufacturer_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.nutritional nutritional {
            get {
                return this.nutritionalField;
            }
            set {
                if ((object.ReferenceEquals(this.nutritionalField, value) != true)) {
                    this.nutritionalField = value;
                    this.RaisePropertyChanged("nutritional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pack {
            get {
                return this.packField;
            }
            set {
                if ((object.ReferenceEquals(this.packField, value) != true)) {
                    this.packField = value;
                    this.RaisePropertyChanged("pack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.ProductImage[] productimages {
            get {
                return this.productimagesField;
            }
            set {
                if ((object.ReferenceEquals(this.productimagesField, value) != true)) {
                    this.productimagesField = value;
                    this.RaisePropertyChanged("productimages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                if ((object.ReferenceEquals(this.sizeField, value) != true)) {
                    this.sizeField = value;
                    this.RaisePropertyChanged("size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string temp_zone {
            get {
                return this.temp_zoneField;
            }
            set {
                if ((object.ReferenceEquals(this.temp_zoneField, value) != true)) {
                    this.temp_zoneField = value;
                    this.RaisePropertyChanged("temp_zone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string upc {
            get {
                return this.upcField;
            }
            set {
                if ((object.ReferenceEquals(this.upcField, value) != true)) {
                    this.upcField = value;
                    this.RaisePropertyChanged("upc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_num {
            get {
                return this.vendor_numField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_numField, value) != true)) {
                    this.vendor_numField = value;
                    this.RaisePropertyChanged("vendor_num");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseProductInfo", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KeithLink.Ext.Pipeline.ItemPrice.PipelineService.product))]
    public partial class BaseProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brand_control_labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brand_extended_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string casepriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string childnutritionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool favoriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string itemnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nonstockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string notesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string packagepriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string replaceditemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string replacementitemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                if ((object.ReferenceEquals(this.brandField, value) != true)) {
                    this.brandField = value;
                    this.RaisePropertyChanged("brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand_control_label {
            get {
                return this.brand_control_labelField;
            }
            set {
                if ((object.ReferenceEquals(this.brand_control_labelField, value) != true)) {
                    this.brand_control_labelField = value;
                    this.RaisePropertyChanged("brand_control_label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brand_extended_description {
            get {
                return this.brand_extended_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.brand_extended_descriptionField, value) != true)) {
                    this.brand_extended_descriptionField = value;
                    this.RaisePropertyChanged("brand_extended_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caseprice {
            get {
                return this.casepriceField;
            }
            set {
                if ((object.ReferenceEquals(this.casepriceField, value) != true)) {
                    this.casepriceField = value;
                    this.RaisePropertyChanged("caseprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string childnutrition {
            get {
                return this.childnutritionField;
            }
            set {
                if ((object.ReferenceEquals(this.childnutritionField, value) != true)) {
                    this.childnutritionField = value;
                    this.RaisePropertyChanged("childnutrition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool favorite {
            get {
                return this.favoriteField;
            }
            set {
                if ((this.favoriteField.Equals(value) != true)) {
                    this.favoriteField = value;
                    this.RaisePropertyChanged("favorite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string itemnumber {
            get {
                return this.itemnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.itemnumberField, value) != true)) {
                    this.itemnumberField = value;
                    this.RaisePropertyChanged("itemnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nonstock {
            get {
                return this.nonstockField;
            }
            set {
                if ((object.ReferenceEquals(this.nonstockField, value) != true)) {
                    this.nonstockField = value;
                    this.RaisePropertyChanged("nonstock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string packageprice {
            get {
                return this.packagepriceField;
            }
            set {
                if ((object.ReferenceEquals(this.packagepriceField, value) != true)) {
                    this.packagepriceField = value;
                    this.RaisePropertyChanged("packageprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string replaceditem {
            get {
                return this.replaceditemField;
            }
            set {
                if ((object.ReferenceEquals(this.replaceditemField, value) != true)) {
                    this.replaceditemField = value;
                    this.RaisePropertyChanged("replaceditem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string replacementitem {
            get {
                return this.replacementitemField;
            }
            set {
                if ((object.ReferenceEquals(this.replacementitemField, value) != true)) {
                    this.replacementitemField = value;
                    this.RaisePropertyChanged("replacementitem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nutritional", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class nutritional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KeithLink.Ext.Pipeline.ItemPrice.PipelineService.allergen allergensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string brandownerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryoforiginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KeithLink.Ext.Pipeline.ItemPrice.PipelineService.diet[] dietField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string grossweightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string handlinginstructionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string heightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ingredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string marketingmessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string moreinformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KeithLink.Ext.Pipeline.ItemPrice.PipelineService.nutrition[] nutritionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servingsizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servingsizeuomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servingsperpackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servingsuggestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shelfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string storagetempField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unitmeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string unitspercaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string volumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string widthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.allergen allergens {
            get {
                return this.allergensField;
            }
            set {
                if ((object.ReferenceEquals(this.allergensField, value) != true)) {
                    this.allergensField = value;
                    this.RaisePropertyChanged("allergens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string brandowner {
            get {
                return this.brandownerField;
            }
            set {
                if ((object.ReferenceEquals(this.brandownerField, value) != true)) {
                    this.brandownerField = value;
                    this.RaisePropertyChanged("brandowner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryoforigin {
            get {
                return this.countryoforiginField;
            }
            set {
                if ((object.ReferenceEquals(this.countryoforiginField, value) != true)) {
                    this.countryoforiginField = value;
                    this.RaisePropertyChanged("countryoforigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.diet[] diet {
            get {
                return this.dietField;
            }
            set {
                if ((object.ReferenceEquals(this.dietField, value) != true)) {
                    this.dietField = value;
                    this.RaisePropertyChanged("diet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grossweight {
            get {
                return this.grossweightField;
            }
            set {
                if ((object.ReferenceEquals(this.grossweightField, value) != true)) {
                    this.grossweightField = value;
                    this.RaisePropertyChanged("grossweight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string handlinginstruction {
            get {
                return this.handlinginstructionField;
            }
            set {
                if ((object.ReferenceEquals(this.handlinginstructionField, value) != true)) {
                    this.handlinginstructionField = value;
                    this.RaisePropertyChanged("handlinginstruction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string height {
            get {
                return this.heightField;
            }
            set {
                if ((object.ReferenceEquals(this.heightField, value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ingredients {
            get {
                return this.ingredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ingredientsField, value) != true)) {
                    this.ingredientsField = value;
                    this.RaisePropertyChanged("ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string length {
            get {
                return this.lengthField;
            }
            set {
                if ((object.ReferenceEquals(this.lengthField, value) != true)) {
                    this.lengthField = value;
                    this.RaisePropertyChanged("length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string marketingmessage {
            get {
                return this.marketingmessageField;
            }
            set {
                if ((object.ReferenceEquals(this.marketingmessageField, value) != true)) {
                    this.marketingmessageField = value;
                    this.RaisePropertyChanged("marketingmessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moreinformation {
            get {
                return this.moreinformationField;
            }
            set {
                if ((object.ReferenceEquals(this.moreinformationField, value) != true)) {
                    this.moreinformationField = value;
                    this.RaisePropertyChanged("moreinformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.nutrition[] nutrition {
            get {
                return this.nutritionField;
            }
            set {
                if ((object.ReferenceEquals(this.nutritionField, value) != true)) {
                    this.nutritionField = value;
                    this.RaisePropertyChanged("nutrition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string servingsize {
            get {
                return this.servingsizeField;
            }
            set {
                if ((object.ReferenceEquals(this.servingsizeField, value) != true)) {
                    this.servingsizeField = value;
                    this.RaisePropertyChanged("servingsize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string servingsizeuom {
            get {
                return this.servingsizeuomField;
            }
            set {
                if ((object.ReferenceEquals(this.servingsizeuomField, value) != true)) {
                    this.servingsizeuomField = value;
                    this.RaisePropertyChanged("servingsizeuom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string servingsperpack {
            get {
                return this.servingsperpackField;
            }
            set {
                if ((object.ReferenceEquals(this.servingsperpackField, value) != true)) {
                    this.servingsperpackField = value;
                    this.RaisePropertyChanged("servingsperpack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string servingsuggestion {
            get {
                return this.servingsuggestionField;
            }
            set {
                if ((object.ReferenceEquals(this.servingsuggestionField, value) != true)) {
                    this.servingsuggestionField = value;
                    this.RaisePropertyChanged("servingsuggestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shelf {
            get {
                return this.shelfField;
            }
            set {
                if ((object.ReferenceEquals(this.shelfField, value) != true)) {
                    this.shelfField = value;
                    this.RaisePropertyChanged("shelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string storagetemp {
            get {
                return this.storagetempField;
            }
            set {
                if ((object.ReferenceEquals(this.storagetempField, value) != true)) {
                    this.storagetempField = value;
                    this.RaisePropertyChanged("storagetemp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitmeasure {
            get {
                return this.unitmeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.unitmeasureField, value) != true)) {
                    this.unitmeasureField = value;
                    this.RaisePropertyChanged("unitmeasure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitspercase {
            get {
                return this.unitspercaseField;
            }
            set {
                if ((object.ReferenceEquals(this.unitspercaseField, value) != true)) {
                    this.unitspercaseField = value;
                    this.RaisePropertyChanged("unitspercase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string volume {
            get {
                return this.volumeField;
            }
            set {
                if ((object.ReferenceEquals(this.volumeField, value) != true)) {
                    this.volumeField = value;
                    this.RaisePropertyChanged("volume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string width {
            get {
                return this.widthField;
            }
            set {
                if ((object.ReferenceEquals(this.widthField, value) != true)) {
                    this.widthField = value;
                    this.RaisePropertyChanged("width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductImage", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class ProductImage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Height {
            get {
                return this.HeightField;
            }
            set {
                if ((object.ReferenceEquals(this.HeightField, value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Width {
            get {
                return this.WidthField;
            }
            set {
                if ((object.ReferenceEquals(this.WidthField, value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="allergen", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class allergen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] containsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] freefromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] maycontainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] contains {
            get {
                return this.containsField;
            }
            set {
                if ((object.ReferenceEquals(this.containsField, value) != true)) {
                    this.containsField = value;
                    this.RaisePropertyChanged("contains");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] freefrom {
            get {
                return this.freefromField;
            }
            set {
                if ((object.ReferenceEquals(this.freefromField, value) != true)) {
                    this.freefromField = value;
                    this.RaisePropertyChanged("freefrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] maycontain {
            get {
                return this.maycontainField;
            }
            set {
                if ((object.ReferenceEquals(this.maycontainField, value) != true)) {
                    this.maycontainField = value;
                    this.RaisePropertyChanged("maycontain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="diet", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class diet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string diettypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diettype {
            get {
                return this.diettypeField;
            }
            set {
                if ((object.ReferenceEquals(this.diettypeField, value) != true)) {
                    this.diettypeField = value;
                    this.RaisePropertyChanged("diettype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nutrition", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class nutrition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dailyvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string measurementtypeidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string measurementvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nutrienttypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nutrienttypecodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dailyvalue {
            get {
                return this.dailyvalueField;
            }
            set {
                if ((object.ReferenceEquals(this.dailyvalueField, value) != true)) {
                    this.dailyvalueField = value;
                    this.RaisePropertyChanged("dailyvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string measurementtypeid {
            get {
                return this.measurementtypeidField;
            }
            set {
                if ((object.ReferenceEquals(this.measurementtypeidField, value) != true)) {
                    this.measurementtypeidField = value;
                    this.RaisePropertyChanged("measurementtypeid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string measurementvalue {
            get {
                return this.measurementvalueField;
            }
            set {
                if ((object.ReferenceEquals(this.measurementvalueField, value) != true)) {
                    this.measurementvalueField = value;
                    this.RaisePropertyChanged("measurementvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nutrienttype {
            get {
                return this.nutrienttypeField;
            }
            set {
                if ((object.ReferenceEquals(this.nutrienttypeField, value) != true)) {
                    this.nutrienttypeField = value;
                    this.RaisePropertyChanged("nutrienttype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nutrienttypecode {
            get {
                return this.nutrienttypecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.nutrienttypecodeField, value) != true)) {
                    this.nutrienttypecodeField = value;
                    this.RaisePropertyChanged("nutrienttypecode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceReturn", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class PriceReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KeithLink.Ext.Pipeline.ItemPrice.PipelineService.Price[] PricesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.Price[] Prices {
            get {
                return this.PricesField;
            }
            set {
                if ((object.ReferenceEquals(this.PricesField, value) != true)) {
                    this.PricesField = value;
                    this.RaisePropertyChanged("Prices");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Price", Namespace="http://schemas.datacontract.org/2004/07/KeithLink.Svc.Core.Models.SiteCatalog")]
    [System.SerializableAttribute()]
    public partial class Price : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CasePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PackagePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchIdField, value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CasePrice {
            get {
                return this.CasePriceField;
            }
            set {
                if ((this.CasePriceField.Equals(value) != true)) {
                    this.CasePriceField = value;
                    this.RaisePropertyChanged("CasePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNumber {
            get {
                return this.CustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNumberField, value) != true)) {
                    this.CustomerNumberField = value;
                    this.RaisePropertyChanged("CustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PackagePrice {
            get {
                return this.PackagePriceField;
            }
            set {
                if ((this.PackagePriceField.Equals(value) != true)) {
                    this.PackagePriceField = value;
                    this.RaisePropertyChanged("PackagePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PipelineService.IPipelineService")]
    public interface IPipelineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetPrices", ReplyAction="http://tempuri.org/IPipelineService/GetPricesResponse")]
        KeithLink.Ext.Pipeline.ItemPrice.PipelineService.PriceReturn GetPrices(string BranchId, string customerNumber, System.DateTime shipDate, KeithLink.Ext.Pipeline.ItemPrice.PipelineService.product[] products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPipelineService/GetPrices", ReplyAction="http://tempuri.org/IPipelineService/GetPricesResponse")]
        System.Threading.Tasks.Task<KeithLink.Ext.Pipeline.ItemPrice.PipelineService.PriceReturn> GetPricesAsync(string BranchId, string customerNumber, System.DateTime shipDate, KeithLink.Ext.Pipeline.ItemPrice.PipelineService.product[] products);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPipelineServiceChannel : KeithLink.Ext.Pipeline.ItemPrice.PipelineService.IPipelineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PipelineServiceClient : System.ServiceModel.ClientBase<KeithLink.Ext.Pipeline.ItemPrice.PipelineService.IPipelineService>, KeithLink.Ext.Pipeline.ItemPrice.PipelineService.IPipelineService {
        
        public PipelineServiceClient() {
        }
        
        public PipelineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PipelineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PipelineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PipelineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KeithLink.Ext.Pipeline.ItemPrice.PipelineService.PriceReturn GetPrices(string BranchId, string customerNumber, System.DateTime shipDate, KeithLink.Ext.Pipeline.ItemPrice.PipelineService.product[] products) {
            return base.Channel.GetPrices(BranchId, customerNumber, shipDate, products);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Ext.Pipeline.ItemPrice.PipelineService.PriceReturn> GetPricesAsync(string BranchId, string customerNumber, System.DateTime shipDate, KeithLink.Ext.Pipeline.ItemPrice.PipelineService.product[] products) {
            return base.Channel.GetPricesAsync(BranchId, customerNumber, shipDate, products);
        }
    }
}
