//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.DsrService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.DsrService.IDsrService")]
    public interface IDsrService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDsrService/GetDsr", ReplyAction="http://tempuri.org/IDsrService/GetDsrResponse")]
        KeithLink.Svc.Core.Models.Profile.Dsr GetDsr(string branchId, string dsrNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDsrService/GetDsr", ReplyAction="http://tempuri.org/IDsrService/GetDsrResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Profile.Dsr> GetDsrAsync(string branchId, string dsrNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDsrServiceChannel : KeithLink.Svc.WebApi.com.benekeith.DsrService.IDsrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DsrServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.DsrService.IDsrService>, KeithLink.Svc.WebApi.com.benekeith.DsrService.IDsrService {
        
        public DsrServiceClient() {
        }
        
        public DsrServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DsrServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DsrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DsrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KeithLink.Svc.Core.Models.Profile.Dsr GetDsr(string branchId, string dsrNumber) {
            return base.Channel.GetDsr(branchId, dsrNumber);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Profile.Dsr> GetDsrAsync(string branchId, string dsrNumber) {
            return base.Channel.GetDsrAsync(branchId, dsrNumber);
        }
    }
}
