//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.Impl.keithlink.svc.internalsvc.orderservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="keithlink.svc.internalsvc.orderservice.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/SaveCartAsOrder", ReplyAction="http://tempuri.org/IOrderService/SaveCartAsOrderResponse")]
        string SaveCartAsOrder(System.Guid userId, System.Guid cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/SaveCartAsOrder", ReplyAction="http://tempuri.org/IOrderService/SaveCartAsOrderResponse")]
        System.Threading.Tasks.Task<string> SaveCartAsOrderAsync(System.Guid userId, System.Guid cartId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : KeithLink.Svc.Impl.keithlink.svc.internalsvc.orderservice.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.Impl.keithlink.svc.internalsvc.orderservice.IOrderService>, KeithLink.Svc.Impl.keithlink.svc.internalsvc.orderservice.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveCartAsOrder(System.Guid userId, System.Guid cartId) {
            return base.Channel.SaveCartAsOrder(userId, cartId);
        }
        
        public System.Threading.Tasks.Task<string> SaveCartAsOrderAsync(System.Guid userId, System.Guid cartId) {
            return base.Channel.SaveCartAsOrderAsync(userId, cartId);
        }
    }
}
