//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.Impl.com.benekeith.PricingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.PricingService.PricingSoap")]
    public interface PricingSoap {
        
        // CODEGEN: Generating message contract since element name XmlFile from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculate", ReplyAction="*")]
        KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponse Calculate(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculate", ReplyAction="*")]
        System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponse> CalculateAsync(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest request);
        
        // CODEGEN: Generating message contract since element name XmlRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatePricingForNonBekItems", ReplyAction="*")]
        KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponse CalculatePricingForNonBekItems(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculatePricingForNonBekItems", ReplyAction="*")]
        System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponse> CalculatePricingForNonBekItemsAsync(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculate", Namespace="http://tempuri.org/", Order=0)]
        public KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequestBody Body;
        
        public CalculateRequest() {
        }
        
        public CalculateRequest(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlFile;
        
        public CalculateRequestBody() {
        }
        
        public CalculateRequestBody(string XmlFile) {
            this.XmlFile = XmlFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponseBody Body;
        
        public CalculateResponse() {
        }
        
        public CalculateResponse(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculateResult;
        
        public CalculateResponseBody() {
        }
        
        public CalculateResponseBody(string CalculateResult) {
            this.CalculateResult = CalculateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePricingForNonBekItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePricingForNonBekItems", Namespace="http://tempuri.org/", Order=0)]
        public KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequestBody Body;
        
        public CalculatePricingForNonBekItemsRequest() {
        }
        
        public CalculatePricingForNonBekItemsRequest(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculatePricingForNonBekItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlRequest;
        
        public CalculatePricingForNonBekItemsRequestBody() {
        }
        
        public CalculatePricingForNonBekItemsRequestBody(string XmlRequest) {
            this.XmlRequest = XmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatePricingForNonBekItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatePricingForNonBekItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponseBody Body;
        
        public CalculatePricingForNonBekItemsResponse() {
        }
        
        public CalculatePricingForNonBekItemsResponse(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalculatePricingForNonBekItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalculatePricingForNonBekItemsResult;
        
        public CalculatePricingForNonBekItemsResponseBody() {
        }
        
        public CalculatePricingForNonBekItemsResponseBody(string CalculatePricingForNonBekItemsResult) {
            this.CalculatePricingForNonBekItemsResult = CalculatePricingForNonBekItemsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PricingSoapChannel : KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PricingSoapClient : System.ServiceModel.ClientBase<KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap>, KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap {
        
        public PricingSoapClient() {
        }
        
        public PricingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PricingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PricingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PricingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponse KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap.Calculate(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest request) {
            return base.Channel.Calculate(request);
        }
        
        public string Calculate(string XmlFile) {
            KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest inValue = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest();
            inValue.Body = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequestBody();
            inValue.Body.XmlFile = XmlFile;
            KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponse retVal = ((KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap)(this)).Calculate(inValue);
            return retVal.Body.CalculateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponse> KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap.CalculateAsync(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest request) {
            return base.Channel.CalculateAsync(request);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateResponse> CalculateAsync(string XmlFile) {
            KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest inValue = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequest();
            inValue.Body = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculateRequestBody();
            inValue.Body.XmlFile = XmlFile;
            return ((KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap)(this)).CalculateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponse KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap.CalculatePricingForNonBekItems(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest request) {
            return base.Channel.CalculatePricingForNonBekItems(request);
        }
        
        public string CalculatePricingForNonBekItems(string XmlRequest) {
            KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest inValue = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest();
            inValue.Body = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponse retVal = ((KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap)(this)).CalculatePricingForNonBekItems(inValue);
            return retVal.Body.CalculatePricingForNonBekItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponse> KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap.CalculatePricingForNonBekItemsAsync(KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest request) {
            return base.Channel.CalculatePricingForNonBekItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsResponse> CalculatePricingForNonBekItemsAsync(string XmlRequest) {
            KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest inValue = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequest();
            inValue.Body = new KeithLink.Svc.Impl.com.benekeith.PricingService.CalculatePricingForNonBekItemsRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            return ((KeithLink.Svc.Impl.com.benekeith.PricingService.PricingSoap)(this)).CalculatePricingForNonBekItemsAsync(inValue);
        }
    }
}
