//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.Impl.com.benekeith.ShipDateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.ShipDateService.ShipDateSoap")]
    public interface ShipDateSoap {
        
        // CODEGEN: Generating message contract since element name XmlRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipDates", ReplyAction="*")]
        KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponse GetShipDates(KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetShipDates", ReplyAction="*")]
        System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponse> GetShipDatesAsync(KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipDatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipDates", Namespace="http://tempuri.org/", Order=0)]
        public KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequestBody Body;
        
        public GetShipDatesRequest() {
        }
        
        public GetShipDatesRequest(KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetShipDatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlRequest;
        
        public GetShipDatesRequestBody() {
        }
        
        public GetShipDatesRequestBody(string XmlRequest) {
            this.XmlRequest = XmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipDatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipDatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponseBody Body;
        
        public GetShipDatesResponse() {
        }
        
        public GetShipDatesResponse(KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetShipDatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetShipDatesResult;
        
        public GetShipDatesResponseBody() {
        }
        
        public GetShipDatesResponseBody(string GetShipDatesResult) {
            this.GetShipDatesResult = GetShipDatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShipDateSoapChannel : KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShipDateSoapClient : System.ServiceModel.ClientBase<KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap>, KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap {
        
        public ShipDateSoapClient() {
        }
        
        public ShipDateSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShipDateSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShipDateSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShipDateSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponse KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap.GetShipDates(KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest request) {
            return base.Channel.GetShipDates(request);
        }
        
        public string GetShipDates(string XmlRequest) {
            KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest inValue = new KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest();
            inValue.Body = new KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponse retVal = ((KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap)(this)).GetShipDates(inValue);
            return retVal.Body.GetShipDatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponse> KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap.GetShipDatesAsync(KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest request) {
            return base.Channel.GetShipDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesResponse> GetShipDatesAsync(string XmlRequest) {
            KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest inValue = new KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequest();
            inValue.Body = new KeithLink.Svc.Impl.com.benekeith.ShipDateService.GetShipDatesRequestBody();
            inValue.Body.XmlRequest = XmlRequest;
            return ((KeithLink.Svc.Impl.com.benekeith.ShipDateService.ShipDateSoap)(this)).GetShipDatesAsync(inValue);
        }
    }
}
