CREATE TABLE [ETL].[Staging_UNFIProducts] (
    [WarehouseNumber]      INT            NULL,
    [Description]          VARCHAR (150)  NULL,
    [Brand]                VARCHAR (150)  NULL,
    [CLength]              DECIMAL (18)   NULL,
    [CWidth]               DECIMAL (9, 3) NULL,
    [CHeight]              DECIMAL (9, 3) NULL,
    [TempControl]          VARCHAR (50)   NULL,
    [UnitOfSale]           VARCHAR (50)   NULL,
    [CatalogDept]          VARCHAR (50)   NULL,
    [ShipMinExpire]        VARCHAR (50)   NULL,
    [ProductNumber]        VARCHAR (10)   NULL,
    [MinOrder]             INT            NULL,
    [VendorCasesPerTier]   INT            NULL,
    [VendorTiersPerPallet] INT            NULL,
    [VendorCasesPerPallet] INT            NULL,
    [CaseQuantity]         INT            NULL,
    [PutUp]                VARCHAR (50)   NULL,
    [ContSize]             DECIMAL (9, 3) NULL,
    [ContUnit]             VARCHAR (50)   NULL,
    [TCSCode]              VARCHAR (50)   NULL,
    [RetailUPC]            VARCHAR (50)   NULL,
    [CaseUPC]              VARCHAR (50)   NULL,
    [Weight]               DECIMAL (9, 3) NULL,
    [PLength]              DECIMAL (9, 3) NULL,
    [PHeight]              DECIMAL (9, 3) NULL,
    [PWidth]               DECIMAL (9, 3) NULL,
    [Status]               VARCHAR (50)   NULL,
    [Type]                 VARCHAR (50)   NULL,
    [Category]             VARCHAR (50)   NULL,
    [Subgroup]             VARCHAR (50)   NULL,
    [EachPrice]            DECIMAL (9, 2) NULL,
    [CasePrice]            DECIMAL (9, 2) NULL,
    [Flag1]                VARCHAR (50)   NULL,
    [Flag2]                VARCHAR (50)   NULL,
    [Flag3]                VARCHAR (50)   NULL,
    [Flag4]                VARCHAR (50)   NULL,
    [OnHandQty]            INT            NULL,
    [Vendor]               VARCHAR (150)  NULL,
    [StockedInBranches]    VARCHAR (50)   NULL
);

