CREATE TABLE [ETL].[Staging_ItemData] (
    [BranchId]          CHAR (3)     NOT NULL,
    [ItemId]            CHAR (6)     NOT NULL,
    [Name]              VARCHAR (30) NULL,
    [Description]       VARCHAR (30) NULL,
    [Brand]             VARCHAR (8)  NULL,
    [Pack]              CHAR (4)     NULL,
    [Size]              VARCHAR (8)  NULL,
    [UPC]               VARCHAR (14) NULL,
    [MfrNumber]         VARCHAR (10) NULL,
    [MfrName]           VARCHAR (30) NULL,
    [Cases]             INT          NULL,
    [Package]           INT          NULL,
    [PreferredItemCode] CHAR (1)     NULL,
    [CategoryId]        CHAR (6)     NULL,
    [ItemType]          CHAR (1)     NULL,
    [Status1]           CHAR (1)     NULL,
    [Status2]           CHAR (1)     NULL,
    [ICSEOnly]          CHAR (1)     NULL,
    [SpecialOrderItem]  CHAR (1)     NULL,
    [Vendor1]           CHAR (6)     NULL,
    [Vendor2]           CHAR (6)     NULL,
    [Class]             CHAR (2)     NULL,
    [CatMgr]            CHAR (2)     NULL,
    [HowPrice]          CHAR (1)     NULL,
    [Buyer]             CHAR (2)     NULL,
    [Kosher]            CHAR (1)     NULL,
    [PVTLbl]            CHAR (1)     NULL,
    [MaxSmrt]           CHAR (2)     NULL,
    [OrderTiHi]         INT          NULL,
    [TiHi]              INT          NULL,
    [DateDiscontinued]  INT          NULL,
    [Dtelstal]          INT          NULL,
    [DTELstPO]          INT          NULL,
    [GrossWeight]       INT          NULL,
    [NetWeight]         INT          NULL,
    [ShelfLife]         INT          NULL,
    [DateSensitiveType] CHAR (1)     NULL,
    [Country]           CHAR (10)    NULL,
    [Length]            INT          NULL,
    [Width]             INT          NULL,
    [Height]            INT          NULL,
    [Cube]              INT          NULL,
    [MinTemp]           INT          NULL,
    [MaxTemp]           INT          NULL,
    [GDSNSync]          CHAR (1)     NULL,
    [GuaranteedDays]    INT          NULL,
    [MasterPack]        INT          NULL,
    [ReplacementItem]   CHAR (6)     NULL,
    [ReplacedItem]      CHAR (6)     NULL,
    [TempZone]          CHAR (1)     NULL,
    [CNDoc]             CHAR (1)     NULL,
    [HACCP]             CHAR (1)     NULL,
    [HACCPDoce]         CHAR (5)     NULL,
    [FDAProductFlag]    CHAR (1)     NULL,
    [FPLength]          INT          NULL,
    [FPWidth]           INT          NULL,
    [FPHeight]          INT          NULL,
    [FPGrossWt]         INT          NULL,
    [FPNetWt]           INT          NULL,
    [FPCube]            INT          NULL,
    [NonStock]          CHAR (1)     NULL
);

