CREATE TABLE [ETL].[Staging_FSE_ProductSpec] (
    [Gtin]                    CHAR (14)       NULL,
    [PackageGtin]             CHAR (14)       NULL,
    [BekItemNumber]           CHAR (6)        NULL,
    [Active]                  BIT             NULL,
    [ProductType]             VARCHAR (20)    NULL,
    [ProductShortDesc]        VARCHAR (70)    NULL,
    [ProductAdditionalDesc]   VARCHAR (MAX)   NULL,
    [ManufacturerItemNumber]  VARCHAR (30)    NULL,
    [UnitsPerCase]            INT             NULL,
    [UnitMeasure]             DECIMAL (20, 3) NULL,
    [UnitMeasureUOM]          VARCHAR (3)     NULL,
    [GrossWeight]             DECIMAL (20, 3) NULL,
    [NetWeight]               DECIMAL (20, 3) NULL,
    [Length]                  DECIMAL (20, 3) NULL,
    [Width]                   DECIMAL (20, 3) NULL,
    [Height]                  DECIMAL (20, 3) NULL,
    [Volume]                  DECIMAL (20, 3) NULL,
    [TiHi]                    VARCHAR (250)   NULL,
    [Shelf]                   INT             NULL,
    [StorageTemp]             VARCHAR (35)    NULL,
    [ServingsPerPack]         INT             NULL,
    [ServingSuggestion]       VARCHAR (MAX)   NULL,
    [MoreInformation]         VARCHAR (35)    NULL,
    [MarketingMessage]        VARCHAR (MAX)   NULL,
    [ServingSize]             DECIMAL (20, 3) NULL,
    [ServingSizeUOM]          VARCHAR (3)     NULL,
    [Ingredients]             VARCHAR (MAX)   NULL,
    [Brand]                   VARCHAR (35)    NULL,
    [BrandOwner]              VARCHAR (MAX)   NULL,
    [CountryOfOrigin]         VARCHAR (100)   NULL,
    [ContryOfOriginName]      VARCHAR (100)   NULL,
    [PreparationInstructions] VARCHAR (MAX)   NULL,
    [HandlingInstruction]     VARCHAR (MAX)   NULL
);

