//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(KeithLink.Svc.Impl.Repository.EF.Operational.BEKDBContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetse95771c25d6311c8555503acdae6391dd8b1de60dd7d1d159872ebde2bf72b2f))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySetse95771c25d6311c8555503acdae6391dd8b1de60dd7d1d159872ebde2bf72b2f : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "e95771c25d6311c8555503acdae6391dd8b1de60dd7d1d159872ebde2bf72b2f"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.BranchSupport")
            {
                return GetView0();
            }

            if (extentName == "BEKDBContext.BranchSupports")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.ContentItem")
            {
                return GetView2();
            }

            if (extentName == "BEKDBContext.ContentItems")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.CustomerTopic")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.UserTopicSubscription")
            {
                return GetView5();
            }

            if (extentName == "BEKDBContext.CustomerTopics")
            {
                return GetView6();
            }

            if (extentName == "BEKDBContext.UserTopicSubscriptions")
            {
                return GetView7();
            }

            if (extentName == "BEKDBContext.CustomerTopic_Subscriptions")
            {
                return GetView8();
            }

            if (extentName == "CodeFirstDatabase.Dsr")
            {
                return GetView9();
            }

            if (extentName == "BEKDBContext.Dsrs")
            {
                return GetView10();
            }

            if (extentName == "CodeFirstDatabase.ExportSetting")
            {
                return GetView11();
            }

            if (extentName == "BEKDBContext.ExportSettings")
            {
                return GetView12();
            }

            if (extentName == "CodeFirstDatabase.InvoiceItem")
            {
                return GetView13();
            }

            if (extentName == "CodeFirstDatabase.Invoice")
            {
                return GetView14();
            }

            if (extentName == "BEKDBContext.InvoiceItems")
            {
                return GetView15();
            }

            if (extentName == "BEKDBContext.Invoices")
            {
                return GetView16();
            }

            if (extentName == "CodeFirstDatabase.ListItem")
            {
                return GetView17();
            }

            if (extentName == "CodeFirstDatabase.List")
            {
                return GetView18();
            }

            if (extentName == "CodeFirstDatabase.ListShare")
            {
                return GetView19();
            }

            if (extentName == "BEKDBContext.ListItems")
            {
                return GetView20();
            }

            if (extentName == "BEKDBContext.List_Items")
            {
                return GetView21();
            }

            if (extentName == "BEKDBContext.Lists")
            {
                return GetView22();
            }

            if (extentName == "BEKDBContext.ListShares")
            {
                return GetView23();
            }

            if (extentName == "BEKDBContext.ListShare_SharedList")
            {
                return GetView24();
            }

            if (extentName == "CodeFirstDatabase.MessageTemplate")
            {
                return GetView25();
            }

            if (extentName == "BEKDBContext.MessageTemplates")
            {
                return GetView26();
            }

            if (extentName == "CodeFirstDatabase.OrderHistoryDetail")
            {
                return GetView27();
            }

            if (extentName == "CodeFirstDatabase.OrderHistoryHeader")
            {
                return GetView28();
            }

            if (extentName == "BEKDBContext.OrderHistoryDetails")
            {
                return GetView29();
            }

            if (extentName == "BEKDBContext.OrderHistoryHeader_OrderDetails")
            {
                return GetView30();
            }

            if (extentName == "BEKDBContext.OrderHistoryHeaders")
            {
                return GetView31();
            }

            if (extentName == "CodeFirstDatabase.Term")
            {
                return GetView32();
            }

            if (extentName == "BEKDBContext.Terms")
            {
                return GetView33();
            }

            if (extentName == "CodeFirstDatabase.UserActiveCart")
            {
                return GetView34();
            }

            if (extentName == "BEKDBContext.UserActiveCarts")
            {
                return GetView35();
            }

            if (extentName == "CodeFirstDatabase.UserMessage")
            {
                return GetView36();
            }

            if (extentName == "BEKDBContext.UserMessages")
            {
                return GetView37();
            }

            if (extentName == "CodeFirstDatabase.UserMessagingPreference")
            {
                return GetView38();
            }

            if (extentName == "BEKDBContext.UserMessagingPreferences")
            {
                return GetView39();
            }

            if (extentName == "CodeFirstDatabase.UserPushNotificationDevice")
            {
                return GetView40();
            }

            if (extentName == "BEKDBContext.UserPushNotificationDevices")
            {
                return GetView41();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.BranchSupport.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BranchSupport
        [CodeFirstDatabaseSchema.BranchSupport](T1.BranchSupport_Id, T1.BranchSupport_BranchName, T1.BranchSupport_BranchId, T1.BranchSupport_SupportPhoneNumber, T1.BranchSupport_TollFreeNumber, T1.BranchSupport_Email, T1.BranchSupport_CreatedUtc, T1.BranchSupport_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS BranchSupport_Id, 
            T.BranchName AS BranchSupport_BranchName, 
            T.BranchId AS BranchSupport_BranchId, 
            T.SupportPhoneNumber AS BranchSupport_SupportPhoneNumber, 
            T.TollFreeNumber AS BranchSupport_TollFreeNumber, 
            T.Email AS BranchSupport_Email, 
            T.CreatedUtc AS BranchSupport_CreatedUtc, 
            T.ModifiedUtc AS BranchSupport_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.BranchSupports AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.BranchSupports.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BranchSupports
        [KeithLink.Svc.Impl.Repository.EF.Operational.BranchSupport](T1.BranchSupport_Id, T1.BranchSupport_BranchName, T1.BranchSupport_BranchId, T1.BranchSupport_SupportPhoneNumber, T1.BranchSupport_TollFreeNumber, T1.BranchSupport_Email, T1.BranchSupport_CreatedUtc, T1.BranchSupport_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS BranchSupport_Id, 
            T.BranchName AS BranchSupport_BranchName, 
            T.BranchId AS BranchSupport_BranchId, 
            T.SupportPhoneNumber AS BranchSupport_SupportPhoneNumber, 
            T.TollFreeNumber AS BranchSupport_TollFreeNumber, 
            T.Email AS BranchSupport_Email, 
            T.CreatedUtc AS BranchSupport_CreatedUtc, 
            T.ModifiedUtc AS BranchSupport_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.BranchSupport AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ContentItem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContentItem
        [CodeFirstDatabaseSchema.ContentItem](T1.ContentItem_Id, T1.ContentItem_BranchId, T1.ContentItem_ImageUrl, T1.ContentItem_TagLine, T1.ContentItem_TargetUrlText, T1.ContentItem_TargetUrl, T1.ContentItem_CampaignId, T1.ContentItem_Content, T1.ContentItem_ProductId, T1.ContentItem_IsContentHtml, T1.ContentItem_ActiveDateStart, T1.ContentItem_ActiveDateEnd, T1.ContentItem_CreatedUtc, T1.ContentItem_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS ContentItem_Id, 
            T.BranchId AS ContentItem_BranchId, 
            T.ImageUrl AS ContentItem_ImageUrl, 
            T.TagLine AS ContentItem_TagLine, 
            T.TargetUrlText AS ContentItem_TargetUrlText, 
            T.TargetUrl AS ContentItem_TargetUrl, 
            T.CampaignId AS ContentItem_CampaignId, 
            T.Content AS ContentItem_Content, 
            T.ProductId AS ContentItem_ProductId, 
            T.IsContentHtml AS ContentItem_IsContentHtml, 
            T.ActiveDateStart AS ContentItem_ActiveDateStart, 
            T.ActiveDateEnd AS ContentItem_ActiveDateEnd, 
            T.CreatedUtc AS ContentItem_CreatedUtc, 
            T.ModifiedUtc AS ContentItem_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.ContentItems AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.ContentItems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ContentItems
        [KeithLink.Svc.Impl.Repository.EF.Operational.ContentItem](T1.ContentItem_Id, T1.ContentItem_BranchId, T1.ContentItem_ImageUrl, T1.ContentItem_TagLine, T1.ContentItem_TargetUrlText, T1.ContentItem_TargetUrl, T1.ContentItem_CampaignId, T1.ContentItem_Content, T1.ContentItem_ProductId, T1.ContentItem_IsContentHtml, T1.ContentItem_ActiveDateStart, T1.ContentItem_ActiveDateEnd, T1.ContentItem_CreatedUtc, T1.ContentItem_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS ContentItem_Id, 
            T.BranchId AS ContentItem_BranchId, 
            T.ImageUrl AS ContentItem_ImageUrl, 
            T.TagLine AS ContentItem_TagLine, 
            T.TargetUrlText AS ContentItem_TargetUrlText, 
            T.TargetUrl AS ContentItem_TargetUrl, 
            T.CampaignId AS ContentItem_CampaignId, 
            T.Content AS ContentItem_Content, 
            T.ProductId AS ContentItem_ProductId, 
            T.IsContentHtml AS ContentItem_IsContentHtml, 
            T.ActiveDateStart AS ContentItem_ActiveDateStart, 
            T.ActiveDateEnd AS ContentItem_ActiveDateEnd, 
            T.CreatedUtc AS ContentItem_CreatedUtc, 
            T.ModifiedUtc AS ContentItem_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.ContentItem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.CustomerTopic.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CustomerTopic
        [CodeFirstDatabaseSchema.CustomerTopic](T1.CustomerTopic_Id, T1.CustomerTopic_CustomerNumber, T1.CustomerTopic_ProviderTopicId, T1.CustomerTopic_NotificationType, T1.CustomerTopic_CreatedUtc, T1.CustomerTopic_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS CustomerTopic_Id, 
            T.CustomerNumber AS CustomerTopic_CustomerNumber, 
            T.ProviderTopicId AS CustomerTopic_ProviderTopicId, 
            CAST(T.NotificationType AS [Edm.Int32]) AS CustomerTopic_NotificationType, 
            T.CreatedUtc AS CustomerTopic_CreatedUtc, 
            T.ModifiedUtc AS CustomerTopic_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.CustomerTopics AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserTopicSubscription.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserTopicSubscription
        [CodeFirstDatabaseSchema.UserTopicSubscription](T3.UserTopicSubscription_Id, T3.UserTopicSubscription_UserId, T3.UserTopicSubscription_Channel, T3.UserTopicSubscription_ProviderSubscriptionId, T3.UserTopicSubscription_NotificationEndpoint, T3.UserTopicSubscription_CreatedUtc, T3.UserTopicSubscription_ModifiedUtc, T3.[UserTopicSubscription.CustomerTopic_Id])
    FROM (
        SELECT T1.UserTopicSubscription_Id, T1.UserTopicSubscription_UserId, T1.UserTopicSubscription_Channel, T1.UserTopicSubscription_ProviderSubscriptionId, T1.UserTopicSubscription_NotificationEndpoint, T1.UserTopicSubscription_CreatedUtc, T1.UserTopicSubscription_ModifiedUtc, T2.[UserTopicSubscription.CustomerTopic_Id], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.Id AS UserTopicSubscription_Id, 
                T.UserId AS UserTopicSubscription_UserId, 
                CAST(T.Channel AS [Edm.Int32]) AS UserTopicSubscription_Channel, 
                T.ProviderSubscriptionId AS UserTopicSubscription_ProviderSubscriptionId, 
                T.NotificationEndpoint AS UserTopicSubscription_NotificationEndpoint, 
                T.CreatedUtc AS UserTopicSubscription_CreatedUtc, 
                T.ModifiedUtc AS UserTopicSubscription_ModifiedUtc, 
                True AS _from0
            FROM BEKDBContext.UserTopicSubscriptions AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.CustomerTopic_Subscriptions_Target).Id AS UserTopicSubscription_Id, 
                Key(T.CustomerTopic_Subscriptions_Source).Id AS [UserTopicSubscription.CustomerTopic_Id], 
                True AS _from1
            FROM BEKDBContext.CustomerTopic_Subscriptions AS T) AS T2
            ON T1.UserTopicSubscription_Id = T2.UserTopicSubscription_Id
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.CustomerTopics.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CustomerTopics
        [KeithLink.Svc.Impl.Repository.EF.Operational.CustomerTopic](T1.CustomerTopic_Id, T1.CustomerTopic_CustomerNumber, T1.CustomerTopic_ProviderTopicId, T1.CustomerTopic_NotificationType, T1.CustomerTopic_CreatedUtc, T1.CustomerTopic_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS CustomerTopic_Id, 
            T.CustomerNumber AS CustomerTopic_CustomerNumber, 
            T.ProviderTopicId AS CustomerTopic_ProviderTopicId, 
            CAST(T.NotificationType AS [KeithLink.Svc.Impl.Repository.EF.Operational.NotificationType]) AS CustomerTopic_NotificationType, 
            T.CreatedUtc AS CustomerTopic_CreatedUtc, 
            T.ModifiedUtc AS CustomerTopic_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.CustomerTopic AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.UserTopicSubscriptions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserTopicSubscriptions
        [KeithLink.Svc.Impl.Repository.EF.Operational.UserTopicSubscription](T1.UserTopicSubscription_Id, T1.UserTopicSubscription_UserId, T1.UserTopicSubscription_Channel, T1.UserTopicSubscription_ProviderSubscriptionId, T1.UserTopicSubscription_NotificationEndpoint, T1.UserTopicSubscription_CreatedUtc, T1.UserTopicSubscription_ModifiedUtc) WITH 
        RELATIONSHIP(CREATEREF(BEKDBContext.CustomerTopics, ROW(T1.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source.Id]),[KeithLink.Svc.Impl.Repository.EF.Operational.CustomerTopic]),[KeithLink.Svc.Impl.Repository.EF.Operational.CustomerTopic_Subscriptions],CustomerTopic_Subscriptions_Target,CustomerTopic_Subscriptions_Source) 
    FROM (
        SELECT 
            T.Id AS UserTopicSubscription_Id, 
            T.UserId AS UserTopicSubscription_UserId, 
            CAST(T.Channel AS [KeithLink.Svc.Impl.Repository.EF.Operational.Channel]) AS UserTopicSubscription_Channel, 
            T.ProviderSubscriptionId AS UserTopicSubscription_ProviderSubscriptionId, 
            T.NotificationEndpoint AS UserTopicSubscription_NotificationEndpoint, 
            T.CreatedUtc AS UserTopicSubscription_CreatedUtc, 
            T.ModifiedUtc AS UserTopicSubscription_ModifiedUtc, 
            True AS _from0, 
            T.CustomerTopic_Id AS [CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source.Id]
        FROM CodeFirstDatabase.UserTopicSubscription AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.CustomerTopic_Subscriptions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing CustomerTopic_Subscriptions
        [KeithLink.Svc.Impl.Repository.EF.Operational.CustomerTopic_Subscriptions](T3.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source], T3.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Target])
    FROM (
        SELECT -- Constructing CustomerTopic_Subscriptions_Source
            CreateRef(BEKDBContext.CustomerTopics, row(T2.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.CustomerTopic]) AS [CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source], 
            T2.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Target]
        FROM (
            SELECT -- Constructing CustomerTopic_Subscriptions_Target
                T1.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source.Id], 
                CreateRef(BEKDBContext.UserTopicSubscriptions, row(T1.[CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Target.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.UserTopicSubscription]) AS [CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Target]
            FROM (
                SELECT 
                    T.CustomerTopic_Id AS [CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Source.Id], 
                    T.Id AS [CustomerTopic_Subscriptions.CustomerTopic_Subscriptions_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.UserTopicSubscription AS T
                WHERE T.CustomerTopic_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Dsr.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Dsr
        [CodeFirstDatabaseSchema.Dsr](T1.Dsr_Id, T1.Dsr_DsrNumber, T1.Dsr_EmailAddress, T1.Dsr_BranchId, T1.Dsr_Name, T1.Dsr_Phone, T1.Dsr_ImageUrl, T1.Dsr_CreatedUtc, T1.Dsr_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS Dsr_Id, 
            T.DsrNumber AS Dsr_DsrNumber, 
            T.EmailAddress AS Dsr_EmailAddress, 
            T.BranchId AS Dsr_BranchId, 
            T.Name AS Dsr_Name, 
            T.Phone AS Dsr_Phone, 
            T.ImageUrl AS Dsr_ImageUrl, 
            T.CreatedUtc AS Dsr_CreatedUtc, 
            T.ModifiedUtc AS Dsr_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.Dsrs AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.Dsrs.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Dsrs
        [KeithLink.Svc.Impl.Repository.EF.Operational.Dsr](T1.Dsr_Id, T1.Dsr_DsrNumber, T1.Dsr_EmailAddress, T1.Dsr_BranchId, T1.Dsr_Name, T1.Dsr_Phone, T1.Dsr_ImageUrl, T1.Dsr_CreatedUtc, T1.Dsr_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS Dsr_Id, 
            T.DsrNumber AS Dsr_DsrNumber, 
            T.EmailAddress AS Dsr_EmailAddress, 
            T.BranchId AS Dsr_BranchId, 
            T.Name AS Dsr_Name, 
            T.Phone AS Dsr_Phone, 
            T.ImageUrl AS Dsr_ImageUrl, 
            T.CreatedUtc AS Dsr_CreatedUtc, 
            T.ModifiedUtc AS Dsr_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.Dsr AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ExportSetting.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ExportSetting
        [CodeFirstDatabaseSchema.ExportSetting](T1.ExportSetting_Id, T1.ExportSetting_UserId, T1.ExportSetting_Type, T1.ExportSetting_ListType, T1.ExportSetting_Settings, T1.ExportSetting_ExportFormat, T1.ExportSetting_CreatedUtc, T1.ExportSetting_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS ExportSetting_Id, 
            T.UserId AS ExportSetting_UserId, 
            CAST(T.Type AS [Edm.Int32]) AS ExportSetting_Type, 
            CAST(T.ListType AS [Edm.Int32]) AS ExportSetting_ListType, 
            T.Settings AS ExportSetting_Settings, 
            T.ExportFormat AS ExportSetting_ExportFormat, 
            T.CreatedUtc AS ExportSetting_CreatedUtc, 
            T.ModifiedUtc AS ExportSetting_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.ExportSettings AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.ExportSettings.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ExportSettings
        [KeithLink.Svc.Impl.Repository.EF.Operational.ExportSetting](T1.ExportSetting_Id, T1.ExportSetting_UserId, T1.ExportSetting_Type, T1.ExportSetting_ListType, T1.ExportSetting_Settings, T1.ExportSetting_ExportFormat, T1.ExportSetting_CreatedUtc, T1.ExportSetting_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS ExportSetting_Id, 
            T.UserId AS ExportSetting_UserId, 
            CAST(T.Type AS [KeithLink.Svc.Impl.Repository.EF.Operational.ExportType]) AS ExportSetting_Type, 
            CAST(T.ListType AS [KeithLink.Svc.Impl.Repository.EF.Operational.ListType]) AS ExportSetting_ListType, 
            T.Settings AS ExportSetting_Settings, 
            T.ExportFormat AS ExportSetting_ExportFormat, 
            T.CreatedUtc AS ExportSetting_CreatedUtc, 
            T.ModifiedUtc AS ExportSetting_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.ExportSetting AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.InvoiceItem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing InvoiceItem
        [CodeFirstDatabaseSchema.InvoiceItem](T1.InvoiceItem_Id, T1.InvoiceItem_ItemNumber, T1.InvoiceItem_QuantityOrdered, T1.InvoiceItem_QuantityShipped, T1.InvoiceItem_CatchWeightCode, T1.InvoiceItem_ExtCatchWeight, T1.InvoiceItem_ItemPrice, T1.InvoiceItem_ExtSalesNet, T1.InvoiceItem_LineNumber, T1.InvoiceItem_ClassCode, T1.InvoiceItem_InvoiceId, T1.InvoiceItem_CreatedUtc, T1.InvoiceItem_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS InvoiceItem_Id, 
            T.ItemNumber AS InvoiceItem_ItemNumber, 
            T.QuantityOrdered AS InvoiceItem_QuantityOrdered, 
            T.QuantityShipped AS InvoiceItem_QuantityShipped, 
            T.CatchWeightCode AS InvoiceItem_CatchWeightCode, 
            T.ExtCatchWeight AS InvoiceItem_ExtCatchWeight, 
            T.ItemPrice AS InvoiceItem_ItemPrice, 
            T.ExtSalesNet AS InvoiceItem_ExtSalesNet, 
            T.LineNumber AS InvoiceItem_LineNumber, 
            T.ClassCode AS InvoiceItem_ClassCode, 
            T.InvoiceId AS InvoiceItem_InvoiceId, 
            T.CreatedUtc AS InvoiceItem_CreatedUtc, 
            T.ModifiedUtc AS InvoiceItem_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.InvoiceItems AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Invoice.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Invoice
        [CodeFirstDatabaseSchema.Invoice](T1.Invoice_Id, T1.Invoice_CustomerNumber, T1.Invoice_BranchId, T1.Invoice_InvoiceNumber, T1.Invoice_OrderDate, T1.Invoice_InvoiceDate, T1.Invoice_Type, T1.Invoice_Amount, T1.Invoice_Status, T1.Invoice_DueDate, T1.Invoice_CreatedUtc, T1.Invoice_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS Invoice_Id, 
            T.CustomerNumber AS Invoice_CustomerNumber, 
            T.BranchId AS Invoice_BranchId, 
            T.InvoiceNumber AS Invoice_InvoiceNumber, 
            T.OrderDate AS Invoice_OrderDate, 
            T.InvoiceDate AS Invoice_InvoiceDate, 
            CAST(T.Type AS [Edm.Int32]) AS Invoice_Type, 
            T.Amount AS Invoice_Amount, 
            CAST(T.Status AS [Edm.Int32]) AS Invoice_Status, 
            T.DueDate AS Invoice_DueDate, 
            T.CreatedUtc AS Invoice_CreatedUtc, 
            T.ModifiedUtc AS Invoice_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.Invoices AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.InvoiceItems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing InvoiceItems
        [KeithLink.Svc.Impl.Repository.EF.Operational.InvoiceItem](T1.InvoiceItem_Id, T1.InvoiceItem_ItemNumber, T1.InvoiceItem_QuantityOrdered, T1.InvoiceItem_QuantityShipped, T1.InvoiceItem_CatchWeightCode, T1.InvoiceItem_ExtCatchWeight, T1.InvoiceItem_ItemPrice, T1.InvoiceItem_ExtSalesNet, T1.InvoiceItem_LineNumber, T1.InvoiceItem_ClassCode, T1.InvoiceItem_InvoiceId, T1.InvoiceItem_CreatedUtc, T1.InvoiceItem_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS InvoiceItem_Id, 
            T.ItemNumber AS InvoiceItem_ItemNumber, 
            T.QuantityOrdered AS InvoiceItem_QuantityOrdered, 
            T.QuantityShipped AS InvoiceItem_QuantityShipped, 
            T.CatchWeightCode AS InvoiceItem_CatchWeightCode, 
            T.ExtCatchWeight AS InvoiceItem_ExtCatchWeight, 
            T.ItemPrice AS InvoiceItem_ItemPrice, 
            T.ExtSalesNet AS InvoiceItem_ExtSalesNet, 
            T.LineNumber AS InvoiceItem_LineNumber, 
            T.ClassCode AS InvoiceItem_ClassCode, 
            T.InvoiceId AS InvoiceItem_InvoiceId, 
            T.CreatedUtc AS InvoiceItem_CreatedUtc, 
            T.ModifiedUtc AS InvoiceItem_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.InvoiceItem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.Invoices.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Invoices
        [KeithLink.Svc.Impl.Repository.EF.Operational.Invoice](T1.Invoice_Id, T1.Invoice_CustomerNumber, T1.Invoice_BranchId, T1.Invoice_InvoiceNumber, T1.Invoice_OrderDate, T1.Invoice_InvoiceDate, T1.Invoice_Type, T1.Invoice_Amount, T1.Invoice_Status, T1.Invoice_DueDate, T1.Invoice_CreatedUtc, T1.Invoice_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS Invoice_Id, 
            T.CustomerNumber AS Invoice_CustomerNumber, 
            T.BranchId AS Invoice_BranchId, 
            T.InvoiceNumber AS Invoice_InvoiceNumber, 
            T.OrderDate AS Invoice_OrderDate, 
            T.InvoiceDate AS Invoice_InvoiceDate, 
            CAST(T.Type AS [KeithLink.Svc.Impl.Repository.EF.Operational.InvoiceType]) AS Invoice_Type, 
            T.Amount AS Invoice_Amount, 
            CAST(T.Status AS [KeithLink.Svc.Impl.Repository.EF.Operational.InvoiceStatus]) AS Invoice_Status, 
            T.DueDate AS Invoice_DueDate, 
            T.CreatedUtc AS Invoice_CreatedUtc, 
            T.ModifiedUtc AS Invoice_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.Invoice AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ListItem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ListItem
        [CodeFirstDatabaseSchema.ListItem](T3.ListItem_Id, T3.ListItem_ItemNumber, T3.ListItem_Label, T3.ListItem_Par, T3.ListItem_Note, T3.ListItem_Category, T3.ListItem_Position, T3.ListItem_FromDate, T3.ListItem_ToDate, T3.ListItem_CreatedUtc, T3.ListItem_ModifiedUtc, T3.[ListItem.ParentList_Id])
    FROM (
        SELECT T1.ListItem_Id, T1.ListItem_ItemNumber, T1.ListItem_Label, T1.ListItem_Par, T1.ListItem_Note, T1.ListItem_Category, T1.ListItem_Position, T1.ListItem_FromDate, T1.ListItem_ToDate, T1.ListItem_CreatedUtc, T1.ListItem_ModifiedUtc, T2.[ListItem.ParentList_Id], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.Id AS ListItem_Id, 
                T.ItemNumber AS ListItem_ItemNumber, 
                T.Label AS ListItem_Label, 
                T.Par AS ListItem_Par, 
                T.Note AS ListItem_Note, 
                T.Category AS ListItem_Category, 
                T.Position AS ListItem_Position, 
                T.FromDate AS ListItem_FromDate, 
                T.ToDate AS ListItem_ToDate, 
                T.CreatedUtc AS ListItem_CreatedUtc, 
                T.ModifiedUtc AS ListItem_ModifiedUtc, 
                True AS _from0
            FROM BEKDBContext.ListItems AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.List_Items_Target).Id AS ListItem_Id, 
                Key(T.List_Items_Source).Id AS [ListItem.ParentList_Id], 
                True AS _from1
            FROM BEKDBContext.List_Items AS T) AS T2
            ON T1.ListItem_Id = T2.ListItem_Id
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.List.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing List
        [CodeFirstDatabaseSchema.List](T1.List_Id, T1.List_UserId, T1.List_DisplayName, T1.List_Type, T1.List_CustomerId, T1.List_BranchId, T1.List_AccountNumber, T1.List_ReadOnly, T1.List_CreatedUtc, T1.List_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS List_Id, 
            T.UserId AS List_UserId, 
            T.DisplayName AS List_DisplayName, 
            CAST(T.Type AS [Edm.Int32]) AS List_Type, 
            T.CustomerId AS List_CustomerId, 
            T.BranchId AS List_BranchId, 
            T.AccountNumber AS List_AccountNumber, 
            T.ReadOnly AS List_ReadOnly, 
            T.CreatedUtc AS List_CreatedUtc, 
            T.ModifiedUtc AS List_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.Lists AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.ListShare.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ListShare
        [CodeFirstDatabaseSchema.ListShare](T3.ListShare_Id, T3.ListShare_CustomerId, T3.ListShare_BranchId, T3.ListShare_CreatedUtc, T3.ListShare_ModifiedUtc, T3.[ListShare.SharedList_Id])
    FROM (
        SELECT T1.ListShare_Id, T1.ListShare_CustomerId, T1.ListShare_BranchId, T1.ListShare_CreatedUtc, T1.ListShare_ModifiedUtc, T2.[ListShare.SharedList_Id], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.Id AS ListShare_Id, 
                T.CustomerId AS ListShare_CustomerId, 
                T.BranchId AS ListShare_BranchId, 
                T.CreatedUtc AS ListShare_CreatedUtc, 
                T.ModifiedUtc AS ListShare_ModifiedUtc, 
                True AS _from0
            FROM BEKDBContext.ListShares AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.ListShare_SharedList_Source).Id AS ListShare_Id, 
                Key(T.ListShare_SharedList_Target).Id AS [ListShare.SharedList_Id], 
                True AS _from1
            FROM BEKDBContext.ListShare_SharedList AS T) AS T2
            ON T1.ListShare_Id = T2.ListShare_Id
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.ListItems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ListItems
        [KeithLink.Svc.Impl.Repository.EF.Operational.ListItem](T1.ListItem_Id, T1.ListItem_ItemNumber, T1.ListItem_Label, T1.ListItem_Par, T1.ListItem_Note, T1.ListItem_Category, T1.ListItem_Position, T1.ListItem_FromDate, T1.ListItem_ToDate, T1.ListItem_CreatedUtc, T1.ListItem_ModifiedUtc) WITH 
        RELATIONSHIP(CREATEREF(BEKDBContext.Lists, ROW(T1.[List_Items.List_Items_Source.Id]),[KeithLink.Svc.Impl.Repository.EF.Operational.List]),[KeithLink.Svc.Impl.Repository.EF.Operational.List_Items],List_Items_Target,List_Items_Source) 
    FROM (
        SELECT 
            T.Id AS ListItem_Id, 
            T.ItemNumber AS ListItem_ItemNumber, 
            T.Label AS ListItem_Label, 
            T.Par AS ListItem_Par, 
            T.Note AS ListItem_Note, 
            T.Category AS ListItem_Category, 
            T.Position AS ListItem_Position, 
            T.FromDate AS ListItem_FromDate, 
            T.ToDate AS ListItem_ToDate, 
            T.CreatedUtc AS ListItem_CreatedUtc, 
            T.ModifiedUtc AS ListItem_ModifiedUtc, 
            True AS _from0, 
            T.ParentList_Id AS [List_Items.List_Items_Source.Id]
        FROM CodeFirstDatabase.ListItem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.List_Items.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing List_Items
        [KeithLink.Svc.Impl.Repository.EF.Operational.List_Items](T3.[List_Items.List_Items_Source], T3.[List_Items.List_Items_Target])
    FROM (
        SELECT -- Constructing List_Items_Source
            CreateRef(BEKDBContext.Lists, row(T2.[List_Items.List_Items_Source.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.List]) AS [List_Items.List_Items_Source], 
            T2.[List_Items.List_Items_Target]
        FROM (
            SELECT -- Constructing List_Items_Target
                T1.[List_Items.List_Items_Source.Id], 
                CreateRef(BEKDBContext.ListItems, row(T1.[List_Items.List_Items_Target.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.ListItem]) AS [List_Items.List_Items_Target]
            FROM (
                SELECT 
                    T.ParentList_Id AS [List_Items.List_Items_Source.Id], 
                    T.Id AS [List_Items.List_Items_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.ListItem AS T
                WHERE T.ParentList_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.Lists.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Lists
        [KeithLink.Svc.Impl.Repository.EF.Operational.List](T1.List_Id, T1.List_UserId, T1.List_DisplayName, T1.List_Type, T1.List_CustomerId, T1.List_BranchId, T1.List_AccountNumber, T1.List_ReadOnly, T1.List_CreatedUtc, T1.List_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS List_Id, 
            T.UserId AS List_UserId, 
            T.DisplayName AS List_DisplayName, 
            CAST(T.Type AS [KeithLink.Svc.Impl.Repository.EF.Operational.ListType]) AS List_Type, 
            T.CustomerId AS List_CustomerId, 
            T.BranchId AS List_BranchId, 
            T.AccountNumber AS List_AccountNumber, 
            T.ReadOnly AS List_ReadOnly, 
            T.CreatedUtc AS List_CreatedUtc, 
            T.ModifiedUtc AS List_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.List AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.ListShares.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ListShares
        [KeithLink.Svc.Impl.Repository.EF.Operational.ListShare](T1.ListShare_Id, T1.ListShare_CustomerId, T1.ListShare_BranchId, T1.ListShare_CreatedUtc, T1.ListShare_ModifiedUtc) WITH 
        RELATIONSHIP(CREATEREF(BEKDBContext.Lists, ROW(T1.[ListShare_SharedList.ListShare_SharedList_Target.Id]),[KeithLink.Svc.Impl.Repository.EF.Operational.List]),[KeithLink.Svc.Impl.Repository.EF.Operational.ListShare_SharedList],ListShare_SharedList_Source,ListShare_SharedList_Target) 
    FROM (
        SELECT 
            T.Id AS ListShare_Id, 
            T.CustomerId AS ListShare_CustomerId, 
            T.BranchId AS ListShare_BranchId, 
            T.CreatedUtc AS ListShare_CreatedUtc, 
            T.ModifiedUtc AS ListShare_ModifiedUtc, 
            True AS _from0, 
            T.SharedList_Id AS [ListShare_SharedList.ListShare_SharedList_Target.Id]
        FROM CodeFirstDatabase.ListShare AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.ListShare_SharedList.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ListShare_SharedList
        [KeithLink.Svc.Impl.Repository.EF.Operational.ListShare_SharedList](T3.[ListShare_SharedList.ListShare_SharedList_Source], T3.[ListShare_SharedList.ListShare_SharedList_Target])
    FROM (
        SELECT -- Constructing ListShare_SharedList_Source
            CreateRef(BEKDBContext.ListShares, row(T2.[ListShare_SharedList.ListShare_SharedList_Source.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.ListShare]) AS [ListShare_SharedList.ListShare_SharedList_Source], 
            T2.[ListShare_SharedList.ListShare_SharedList_Target]
        FROM (
            SELECT -- Constructing ListShare_SharedList_Target
                T1.[ListShare_SharedList.ListShare_SharedList_Source.Id], 
                CreateRef(BEKDBContext.Lists, row(T1.[ListShare_SharedList.ListShare_SharedList_Target.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.List]) AS [ListShare_SharedList.ListShare_SharedList_Target]
            FROM (
                SELECT 
                    T.Id AS [ListShare_SharedList.ListShare_SharedList_Source.Id], 
                    T.SharedList_Id AS [ListShare_SharedList.ListShare_SharedList_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.ListShare AS T
                WHERE T.SharedList_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.MessageTemplate.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MessageTemplate
        [CodeFirstDatabaseSchema.MessageTemplate](T1.MessageTemplate_Id, T1.MessageTemplate_TemplateKey, T1.MessageTemplate_Subject, T1.MessageTemplate_IsBodyHtml, T1.MessageTemplate_Body, T1.MessageTemplate_Type, T1.MessageTemplate_CreatedUtc, T1.MessageTemplate_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS MessageTemplate_Id, 
            T.TemplateKey AS MessageTemplate_TemplateKey, 
            T.Subject AS MessageTemplate_Subject, 
            T.IsBodyHtml AS MessageTemplate_IsBodyHtml, 
            T.Body AS MessageTemplate_Body, 
            CAST(T.Type AS [Edm.Int32]) AS MessageTemplate_Type, 
            T.CreatedUtc AS MessageTemplate_CreatedUtc, 
            T.ModifiedUtc AS MessageTemplate_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.MessageTemplates AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.MessageTemplates.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MessageTemplates
        [KeithLink.Svc.Impl.Repository.EF.Operational.MessageTemplate](T1.MessageTemplate_Id, T1.MessageTemplate_TemplateKey, T1.MessageTemplate_Subject, T1.MessageTemplate_IsBodyHtml, T1.MessageTemplate_Body, T1.MessageTemplate_Type, T1.MessageTemplate_CreatedUtc, T1.MessageTemplate_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS MessageTemplate_Id, 
            T.TemplateKey AS MessageTemplate_TemplateKey, 
            T.Subject AS MessageTemplate_Subject, 
            T.IsBodyHtml AS MessageTemplate_IsBodyHtml, 
            T.Body AS MessageTemplate_Body, 
            CAST(T.Type AS [KeithLink.Svc.Impl.Repository.EF.Operational.MessageTemplateType]) AS MessageTemplate_Type, 
            T.CreatedUtc AS MessageTemplate_CreatedUtc, 
            T.ModifiedUtc AS MessageTemplate_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.MessageTemplate AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.OrderHistoryDetail.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrderHistoryDetail
        [CodeFirstDatabaseSchema.OrderHistoryDetail](T3.OrderHistoryDetail_Id, T3.OrderHistoryDetail_BranchId, T3.OrderHistoryDetail_InvoiceNumber, T3.OrderHistoryDetail_LineNumber, T3.OrderHistoryDetail_ItemNumber, T3.OrderHistoryDetail_OrderQuantity, T3.OrderHistoryDetail_ShippedQuantity, T3.OrderHistoryDetail_UnitOfMeasure, T3.OrderHistoryDetail_CatchWeight, T3.OrderHistoryDetail_ItemDeleted, T3.OrderHistoryDetail_SubbedOriginalItemNumber, T3.OrderHistoryDetail_ReplacedOriginalItemNumber, T3.OrderHistoryDetail_ItemStatus, T3.OrderHistoryDetail_TotalShippedWeight, T3.OrderHistoryDetail_SellPrice, T3.OrderHistoryDetail_CreatedUtc, T3.OrderHistoryDetail_ModifiedUtc, T3.[OrderHistoryDetail.OrderHistoryHeader_Id])
    FROM (
        SELECT T1.OrderHistoryDetail_Id, T1.OrderHistoryDetail_BranchId, T1.OrderHistoryDetail_InvoiceNumber, T1.OrderHistoryDetail_LineNumber, T1.OrderHistoryDetail_ItemNumber, T1.OrderHistoryDetail_OrderQuantity, T1.OrderHistoryDetail_ShippedQuantity, T1.OrderHistoryDetail_UnitOfMeasure, T1.OrderHistoryDetail_CatchWeight, T1.OrderHistoryDetail_ItemDeleted, T1.OrderHistoryDetail_SubbedOriginalItemNumber, T1.OrderHistoryDetail_ReplacedOriginalItemNumber, T1.OrderHistoryDetail_ItemStatus, T1.OrderHistoryDetail_TotalShippedWeight, T1.OrderHistoryDetail_SellPrice, T1.OrderHistoryDetail_CreatedUtc, T1.OrderHistoryDetail_ModifiedUtc, T2.[OrderHistoryDetail.OrderHistoryHeader_Id], T1._from0, (T2._from1 AND T2._from1 IS NOT NULL) AS _from1
        FROM  (
            SELECT 
                T.Id AS OrderHistoryDetail_Id, 
                T.BranchId AS OrderHistoryDetail_BranchId, 
                T.InvoiceNumber AS OrderHistoryDetail_InvoiceNumber, 
                T.LineNumber AS OrderHistoryDetail_LineNumber, 
                T.ItemNumber AS OrderHistoryDetail_ItemNumber, 
                T.OrderQuantity AS OrderHistoryDetail_OrderQuantity, 
                T.ShippedQuantity AS OrderHistoryDetail_ShippedQuantity, 
                T.UnitOfMeasure AS OrderHistoryDetail_UnitOfMeasure, 
                T.CatchWeight AS OrderHistoryDetail_CatchWeight, 
                T.ItemDeleted AS OrderHistoryDetail_ItemDeleted, 
                T.SubbedOriginalItemNumber AS OrderHistoryDetail_SubbedOriginalItemNumber, 
                T.ReplacedOriginalItemNumber AS OrderHistoryDetail_ReplacedOriginalItemNumber, 
                T.ItemStatus AS OrderHistoryDetail_ItemStatus, 
                T.TotalShippedWeight AS OrderHistoryDetail_TotalShippedWeight, 
                T.SellPrice AS OrderHistoryDetail_SellPrice, 
                T.CreatedUtc AS OrderHistoryDetail_CreatedUtc, 
                T.ModifiedUtc AS OrderHistoryDetail_ModifiedUtc, 
                True AS _from0
            FROM BEKDBContext.OrderHistoryDetails AS T) AS T1
            LEFT OUTER JOIN (
            SELECT 
                Key(T.OrderHistoryHeader_OrderDetails_Target).Id AS OrderHistoryDetail_Id, 
                Key(T.OrderHistoryHeader_OrderDetails_Source).Id AS [OrderHistoryDetail.OrderHistoryHeader_Id], 
                True AS _from1
            FROM BEKDBContext.OrderHistoryHeader_OrderDetails AS T) AS T2
            ON T1.OrderHistoryDetail_Id = T2.OrderHistoryDetail_Id
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.OrderHistoryHeader.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrderHistoryHeader
        [CodeFirstDatabaseSchema.OrderHistoryHeader](T1.OrderHistoryHeader_Id, T1.OrderHistoryHeader_OrderSystem, T1.OrderHistoryHeader_BranchId, T1.OrderHistoryHeader_CustomerNumber, T1.OrderHistoryHeader_InvoiceNumber, T1.OrderHistoryHeader_DeliveryDate, T1.OrderHistoryHeader_PONumber, T1.OrderHistoryHeader_ControlNumber, T1.OrderHistoryHeader_OrderStatus, T1.OrderHistoryHeader_FutureItems, T1.OrderHistoryHeader_ErrorStatus, T1.OrderHistoryHeader_RouteNumber, T1.OrderHistoryHeader_StopNumber, T1.OrderHistoryHeader_ScheduledDeliveryTime, T1.OrderHistoryHeader_EstimatedDeliveryTime, T1.OrderHistoryHeader_ActualDeliveryTime, T1.OrderHistoryHeader_DeliveryOutOfSequence, T1.OrderHistoryHeader_CreatedUtc, T1.OrderHistoryHeader_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS OrderHistoryHeader_Id, 
            T.OrderSystem AS OrderHistoryHeader_OrderSystem, 
            T.BranchId AS OrderHistoryHeader_BranchId, 
            T.CustomerNumber AS OrderHistoryHeader_CustomerNumber, 
            T.InvoiceNumber AS OrderHistoryHeader_InvoiceNumber, 
            T.DeliveryDate AS OrderHistoryHeader_DeliveryDate, 
            T.PONumber AS OrderHistoryHeader_PONumber, 
            T.ControlNumber AS OrderHistoryHeader_ControlNumber, 
            T.OrderStatus AS OrderHistoryHeader_OrderStatus, 
            T.FutureItems AS OrderHistoryHeader_FutureItems, 
            T.ErrorStatus AS OrderHistoryHeader_ErrorStatus, 
            T.RouteNumber AS OrderHistoryHeader_RouteNumber, 
            T.StopNumber AS OrderHistoryHeader_StopNumber, 
            T.ScheduledDeliveryTime AS OrderHistoryHeader_ScheduledDeliveryTime, 
            T.EstimatedDeliveryTime AS OrderHistoryHeader_EstimatedDeliveryTime, 
            T.ActualDeliveryTime AS OrderHistoryHeader_ActualDeliveryTime, 
            T.DeliveryOutOfSequence AS OrderHistoryHeader_DeliveryOutOfSequence, 
            T.CreatedUtc AS OrderHistoryHeader_CreatedUtc, 
            T.ModifiedUtc AS OrderHistoryHeader_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.OrderHistoryHeaders AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.OrderHistoryDetails.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView29()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrderHistoryDetails
        [KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryDetail](T1.OrderHistoryDetail_Id, T1.OrderHistoryDetail_BranchId, T1.OrderHistoryDetail_InvoiceNumber, T1.OrderHistoryDetail_LineNumber, T1.OrderHistoryDetail_ItemNumber, T1.OrderHistoryDetail_OrderQuantity, T1.OrderHistoryDetail_ShippedQuantity, T1.OrderHistoryDetail_UnitOfMeasure, T1.OrderHistoryDetail_CatchWeight, T1.OrderHistoryDetail_ItemDeleted, T1.OrderHistoryDetail_SubbedOriginalItemNumber, T1.OrderHistoryDetail_ReplacedOriginalItemNumber, T1.OrderHistoryDetail_ItemStatus, T1.OrderHistoryDetail_TotalShippedWeight, T1.OrderHistoryDetail_SellPrice, T1.OrderHistoryDetail_CreatedUtc, T1.OrderHistoryDetail_ModifiedUtc) WITH 
        RELATIONSHIP(CREATEREF(BEKDBContext.OrderHistoryHeaders, ROW(T1.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source.Id]),[KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryHeader]),[KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryHeader_OrderDetails],OrderHistoryHeader_OrderDetails_Target,OrderHistoryHeader_OrderDetails_Source) 
    FROM (
        SELECT 
            T.Id AS OrderHistoryDetail_Id, 
            T.BranchId AS OrderHistoryDetail_BranchId, 
            T.InvoiceNumber AS OrderHistoryDetail_InvoiceNumber, 
            T.LineNumber AS OrderHistoryDetail_LineNumber, 
            T.ItemNumber AS OrderHistoryDetail_ItemNumber, 
            T.OrderQuantity AS OrderHistoryDetail_OrderQuantity, 
            T.ShippedQuantity AS OrderHistoryDetail_ShippedQuantity, 
            T.UnitOfMeasure AS OrderHistoryDetail_UnitOfMeasure, 
            T.CatchWeight AS OrderHistoryDetail_CatchWeight, 
            T.ItemDeleted AS OrderHistoryDetail_ItemDeleted, 
            T.SubbedOriginalItemNumber AS OrderHistoryDetail_SubbedOriginalItemNumber, 
            T.ReplacedOriginalItemNumber AS OrderHistoryDetail_ReplacedOriginalItemNumber, 
            T.ItemStatus AS OrderHistoryDetail_ItemStatus, 
            T.TotalShippedWeight AS OrderHistoryDetail_TotalShippedWeight, 
            T.SellPrice AS OrderHistoryDetail_SellPrice, 
            T.CreatedUtc AS OrderHistoryDetail_CreatedUtc, 
            T.ModifiedUtc AS OrderHistoryDetail_ModifiedUtc, 
            True AS _from0, 
            T.OrderHistoryHeader_Id AS [OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source.Id]
        FROM CodeFirstDatabase.OrderHistoryDetail AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.OrderHistoryHeader_OrderDetails.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView30()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrderHistoryHeader_OrderDetails
        [KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryHeader_OrderDetails](T3.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source], T3.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Target])
    FROM (
        SELECT -- Constructing OrderHistoryHeader_OrderDetails_Source
            CreateRef(BEKDBContext.OrderHistoryHeaders, row(T2.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryHeader]) AS [OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source], 
            T2.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Target]
        FROM (
            SELECT -- Constructing OrderHistoryHeader_OrderDetails_Target
                T1.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source.Id], 
                CreateRef(BEKDBContext.OrderHistoryDetails, row(T1.[OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Target.Id]), [KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryDetail]) AS [OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Target]
            FROM (
                SELECT 
                    T.OrderHistoryHeader_Id AS [OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Source.Id], 
                    T.Id AS [OrderHistoryHeader_OrderDetails.OrderHistoryHeader_OrderDetails_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.OrderHistoryDetail AS T
                WHERE T.OrderHistoryHeader_Id IS NOT NULL
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.OrderHistoryHeaders.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView31()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing OrderHistoryHeaders
        [KeithLink.Svc.Impl.Repository.EF.Operational.OrderHistoryHeader](T1.OrderHistoryHeader_Id, T1.OrderHistoryHeader_OrderSystem, T1.OrderHistoryHeader_BranchId, T1.OrderHistoryHeader_CustomerNumber, T1.OrderHistoryHeader_InvoiceNumber, T1.OrderHistoryHeader_DeliveryDate, T1.OrderHistoryHeader_PONumber, T1.OrderHistoryHeader_ControlNumber, T1.OrderHistoryHeader_OrderStatus, T1.OrderHistoryHeader_FutureItems, T1.OrderHistoryHeader_ErrorStatus, T1.OrderHistoryHeader_RouteNumber, T1.OrderHistoryHeader_StopNumber, T1.OrderHistoryHeader_ScheduledDeliveryTime, T1.OrderHistoryHeader_EstimatedDeliveryTime, T1.OrderHistoryHeader_ActualDeliveryTime, T1.OrderHistoryHeader_DeliveryOutOfSequence, T1.OrderHistoryHeader_CreatedUtc, T1.OrderHistoryHeader_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS OrderHistoryHeader_Id, 
            T.OrderSystem AS OrderHistoryHeader_OrderSystem, 
            T.BranchId AS OrderHistoryHeader_BranchId, 
            T.CustomerNumber AS OrderHistoryHeader_CustomerNumber, 
            T.InvoiceNumber AS OrderHistoryHeader_InvoiceNumber, 
            T.DeliveryDate AS OrderHistoryHeader_DeliveryDate, 
            T.PONumber AS OrderHistoryHeader_PONumber, 
            T.ControlNumber AS OrderHistoryHeader_ControlNumber, 
            T.OrderStatus AS OrderHistoryHeader_OrderStatus, 
            T.FutureItems AS OrderHistoryHeader_FutureItems, 
            T.ErrorStatus AS OrderHistoryHeader_ErrorStatus, 
            T.RouteNumber AS OrderHistoryHeader_RouteNumber, 
            T.StopNumber AS OrderHistoryHeader_StopNumber, 
            T.ScheduledDeliveryTime AS OrderHistoryHeader_ScheduledDeliveryTime, 
            T.EstimatedDeliveryTime AS OrderHistoryHeader_EstimatedDeliveryTime, 
            T.ActualDeliveryTime AS OrderHistoryHeader_ActualDeliveryTime, 
            T.DeliveryOutOfSequence AS OrderHistoryHeader_DeliveryOutOfSequence, 
            T.CreatedUtc AS OrderHistoryHeader_CreatedUtc, 
            T.ModifiedUtc AS OrderHistoryHeader_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.OrderHistoryHeader AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Term.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView32()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Term
        [CodeFirstDatabaseSchema.Term](T1.Term_Id, T1.Term_BranchId, T1.Term_TermCode, T1.Term_Description, T1.Term_Age1, T1.Term_Age2, T1.Term_Age3, T1.Term_Age4, T1.Term_CreatedUtc, T1.Term_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS Term_Id, 
            T.BranchId AS Term_BranchId, 
            T.TermCode AS Term_TermCode, 
            T.Description AS Term_Description, 
            T.Age1 AS Term_Age1, 
            T.Age2 AS Term_Age2, 
            T.Age3 AS Term_Age3, 
            T.Age4 AS Term_Age4, 
            T.CreatedUtc AS Term_CreatedUtc, 
            T.ModifiedUtc AS Term_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.Terms AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.Terms.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView33()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Terms
        [KeithLink.Svc.Impl.Repository.EF.Operational.Term](T1.Term_Id, T1.Term_BranchId, T1.Term_TermCode, T1.Term_Description, T1.Term_Age1, T1.Term_Age2, T1.Term_Age3, T1.Term_Age4, T1.Term_CreatedUtc, T1.Term_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS Term_Id, 
            T.BranchId AS Term_BranchId, 
            T.TermCode AS Term_TermCode, 
            T.Description AS Term_Description, 
            T.Age1 AS Term_Age1, 
            T.Age2 AS Term_Age2, 
            T.Age3 AS Term_Age3, 
            T.Age4 AS Term_Age4, 
            T.CreatedUtc AS Term_CreatedUtc, 
            T.ModifiedUtc AS Term_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.Term AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserActiveCart.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView34()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserActiveCart
        [CodeFirstDatabaseSchema.UserActiveCart](T1.UserActiveCart_Id, T1.UserActiveCart_UserId, T1.UserActiveCart_CartId, T1.UserActiveCart_CustomerId, T1.UserActiveCart_BranchId, T1.UserActiveCart_CreatedUtc, T1.UserActiveCart_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserActiveCart_Id, 
            T.UserId AS UserActiveCart_UserId, 
            T.CartId AS UserActiveCart_CartId, 
            T.CustomerId AS UserActiveCart_CustomerId, 
            T.BranchId AS UserActiveCart_BranchId, 
            T.CreatedUtc AS UserActiveCart_CreatedUtc, 
            T.ModifiedUtc AS UserActiveCart_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.UserActiveCarts AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.UserActiveCarts.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView35()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserActiveCarts
        [KeithLink.Svc.Impl.Repository.EF.Operational.UserActiveCart](T1.UserActiveCart_Id, T1.UserActiveCart_UserId, T1.UserActiveCart_CartId, T1.UserActiveCart_CustomerId, T1.UserActiveCart_BranchId, T1.UserActiveCart_CreatedUtc, T1.UserActiveCart_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserActiveCart_Id, 
            T.UserId AS UserActiveCart_UserId, 
            T.CartId AS UserActiveCart_CartId, 
            T.CustomerId AS UserActiveCart_CustomerId, 
            T.BranchId AS UserActiveCart_BranchId, 
            T.CreatedUtc AS UserActiveCart_CreatedUtc, 
            T.ModifiedUtc AS UserActiveCart_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.UserActiveCart AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserMessage.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView36()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserMessage
        [CodeFirstDatabaseSchema.UserMessage](T1.UserMessage_Id, T1.UserMessage_CustomerNumber, T1.UserMessage_UserId, T1.UserMessage_Label, T1.UserMessage_NotificationType, T1.UserMessage_MessageReadUtc, T1.UserMessage_Subject, T1.UserMessage_Body, T1.UserMessage_Mandatory, T1.UserMessage_CreatedUtc, T1.UserMessage_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserMessage_Id, 
            T.CustomerNumber AS UserMessage_CustomerNumber, 
            T.UserId AS UserMessage_UserId, 
            T.Label AS UserMessage_Label, 
            CAST(T.NotificationType AS [Edm.Int32]) AS UserMessage_NotificationType, 
            T.MessageReadUtc AS UserMessage_MessageReadUtc, 
            T.Subject AS UserMessage_Subject, 
            T.Body AS UserMessage_Body, 
            T.Mandatory AS UserMessage_Mandatory, 
            T.CreatedUtc AS UserMessage_CreatedUtc, 
            T.ModifiedUtc AS UserMessage_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.UserMessages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.UserMessages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView37()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserMessages
        [KeithLink.Svc.Impl.Repository.EF.Operational.UserMessage](T1.UserMessage_Id, T1.UserMessage_CustomerNumber, T1.UserMessage_UserId, T1.UserMessage_Label, T1.UserMessage_NotificationType, T1.UserMessage_MessageReadUtc, T1.UserMessage_Subject, T1.UserMessage_Body, T1.UserMessage_Mandatory, T1.UserMessage_CreatedUtc, T1.UserMessage_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserMessage_Id, 
            T.CustomerNumber AS UserMessage_CustomerNumber, 
            T.UserId AS UserMessage_UserId, 
            T.Label AS UserMessage_Label, 
            CAST(T.NotificationType AS [KeithLink.Svc.Impl.Repository.EF.Operational.NotificationType]) AS UserMessage_NotificationType, 
            T.MessageReadUtc AS UserMessage_MessageReadUtc, 
            T.Subject AS UserMessage_Subject, 
            T.Body AS UserMessage_Body, 
            T.Mandatory AS UserMessage_Mandatory, 
            T.CreatedUtc AS UserMessage_CreatedUtc, 
            T.ModifiedUtc AS UserMessage_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.UserMessage AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserMessagingPreference.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView38()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserMessagingPreference
        [CodeFirstDatabaseSchema.UserMessagingPreference](T1.UserMessagingPreference_Id, T1.UserMessagingPreference_UserId, T1.UserMessagingPreference_NotificationType, T1.UserMessagingPreference_Channel, T1.UserMessagingPreference_CustomerNumber, T1.UserMessagingPreference_BranchId, T1.UserMessagingPreference_CreatedUtc, T1.UserMessagingPreference_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserMessagingPreference_Id, 
            T.UserId AS UserMessagingPreference_UserId, 
            CAST(T.NotificationType AS [Edm.Int32]) AS UserMessagingPreference_NotificationType, 
            CAST(T.Channel AS [Edm.Int32]) AS UserMessagingPreference_Channel, 
            T.CustomerNumber AS UserMessagingPreference_CustomerNumber, 
            T.BranchId AS UserMessagingPreference_BranchId, 
            T.CreatedUtc AS UserMessagingPreference_CreatedUtc, 
            T.ModifiedUtc AS UserMessagingPreference_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.UserMessagingPreferences AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.UserMessagingPreferences.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView39()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserMessagingPreferences
        [KeithLink.Svc.Impl.Repository.EF.Operational.UserMessagingPreference](T1.UserMessagingPreference_Id, T1.UserMessagingPreference_UserId, T1.UserMessagingPreference_NotificationType, T1.UserMessagingPreference_Channel, T1.UserMessagingPreference_CustomerNumber, T1.UserMessagingPreference_BranchId, T1.UserMessagingPreference_CreatedUtc, T1.UserMessagingPreference_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserMessagingPreference_Id, 
            T.UserId AS UserMessagingPreference_UserId, 
            CAST(T.NotificationType AS [KeithLink.Svc.Impl.Repository.EF.Operational.NotificationType]) AS UserMessagingPreference_NotificationType, 
            CAST(T.Channel AS [KeithLink.Svc.Impl.Repository.EF.Operational.Channel]) AS UserMessagingPreference_Channel, 
            T.CustomerNumber AS UserMessagingPreference_CustomerNumber, 
            T.BranchId AS UserMessagingPreference_BranchId, 
            T.CreatedUtc AS UserMessagingPreference_CreatedUtc, 
            T.ModifiedUtc AS UserMessagingPreference_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.UserMessagingPreference AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.UserPushNotificationDevice.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView40()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserPushNotificationDevice
        [CodeFirstDatabaseSchema.UserPushNotificationDevice](T1.UserPushNotificationDevice_Id, T1.UserPushNotificationDevice_UserId, T1.UserPushNotificationDevice_DeviceId, T1.UserPushNotificationDevice_ProviderToken, T1.UserPushNotificationDevice_ProviderEndpointId, T1.UserPushNotificationDevice_DeviceOS, T1.UserPushNotificationDevice_CreatedUtc, T1.UserPushNotificationDevice_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserPushNotificationDevice_Id, 
            T.UserId AS UserPushNotificationDevice_UserId, 
            T.DeviceId AS UserPushNotificationDevice_DeviceId, 
            T.ProviderToken AS UserPushNotificationDevice_ProviderToken, 
            T.ProviderEndpointId AS UserPushNotificationDevice_ProviderEndpointId, 
            CAST(T.DeviceOS AS [Edm.Int32]) AS UserPushNotificationDevice_DeviceOS, 
            T.CreatedUtc AS UserPushNotificationDevice_CreatedUtc, 
            T.ModifiedUtc AS UserPushNotificationDevice_ModifiedUtc, 
            True AS _from0
        FROM BEKDBContext.UserPushNotificationDevices AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for BEKDBContext.UserPushNotificationDevices.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView41()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserPushNotificationDevices
        [KeithLink.Svc.Impl.Repository.EF.Operational.UserPushNotificationDevice](T1.UserPushNotificationDevice_Id, T1.UserPushNotificationDevice_UserId, T1.UserPushNotificationDevice_DeviceId, T1.UserPushNotificationDevice_ProviderToken, T1.UserPushNotificationDevice_ProviderEndpointId, T1.UserPushNotificationDevice_DeviceOS, T1.UserPushNotificationDevice_CreatedUtc, T1.UserPushNotificationDevice_ModifiedUtc)
    FROM (
        SELECT 
            T.Id AS UserPushNotificationDevice_Id, 
            T.UserId AS UserPushNotificationDevice_UserId, 
            T.DeviceId AS UserPushNotificationDevice_DeviceId, 
            T.ProviderToken AS UserPushNotificationDevice_ProviderToken, 
            T.ProviderEndpointId AS UserPushNotificationDevice_ProviderEndpointId, 
            CAST(T.DeviceOS AS [KeithLink.Svc.Impl.Repository.EF.Operational.DeviceOS]) AS UserPushNotificationDevice_DeviceOS, 
            T.CreatedUtc AS UserPushNotificationDevice_CreatedUtc, 
            T.ModifiedUtc AS UserPushNotificationDevice_ModifiedUtc, 
            True AS _from0
        FROM CodeFirstDatabase.UserPushNotificationDevice AS T
    ) AS T1");
        }
    }
}
