//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.Impl.com.benekeith.DivisionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.DivisionService.IDivisionService")]
    public interface IDivisionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDivisionService/ReadBranchSupport", ReplyAction="http://tempuri.org/IDivisionService/ReadBranchSupportResponse")]
        KeithLink.Svc.Core.Models.SiteCatalog.BranchSupportModel[] ReadBranchSupport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDivisionService/ReadBranchSupport", ReplyAction="http://tempuri.org/IDivisionService/ReadBranchSupportResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.SiteCatalog.BranchSupportModel[]> ReadBranchSupportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDivisionServiceChannel : KeithLink.Svc.Impl.com.benekeith.DivisionService.IDivisionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DivisionServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.Impl.com.benekeith.DivisionService.IDivisionService>, KeithLink.Svc.Impl.com.benekeith.DivisionService.IDivisionService {
        
        public DivisionServiceClient() {
        }
        
        public DivisionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DivisionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DivisionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DivisionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KeithLink.Svc.Core.Models.SiteCatalog.BranchSupportModel[] ReadBranchSupport() {
            return base.Channel.ReadBranchSupport();
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.SiteCatalog.BranchSupportModel[]> ReadBranchSupportAsync() {
            return base.Channel.ReadBranchSupportAsync();
        }
    }
}
