//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.InvoiceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.InvoiceService.IInvoiceService")]
    public interface IInvoiceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/ReadInvoices", ReplyAction="http://tempuri.org/IInvoiceService/ReadInvoicesResponse")]
        KeithLink.Svc.Core.Models.Invoices.InvoiceModel[] ReadInvoices(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/ReadInvoices", ReplyAction="http://tempuri.org/IInvoiceService/ReadInvoicesResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceModel[]> ReadInvoicesAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/ReadInvoice", ReplyAction="http://tempuri.org/IInvoiceService/ReadInvoiceResponse")]
        KeithLink.Svc.Core.Models.Invoices.InvoiceModel ReadInvoice(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/ReadInvoice", ReplyAction="http://tempuri.org/IInvoiceService/ReadInvoiceResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceModel> ReadInvoiceAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/ReadTermInformation", ReplyAction="http://tempuri.org/IInvoiceService/ReadTermInformationResponse")]
        KeithLink.Svc.Core.Models.Invoices.TermModel ReadTermInformation(string branchId, string termCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInvoiceService/ReadTermInformation", ReplyAction="http://tempuri.org/IInvoiceService/ReadTermInformationResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.TermModel> ReadTermInformationAsync(string branchId, string termCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInvoiceServiceChannel : KeithLink.Svc.WebApi.com.benekeith.InvoiceService.IInvoiceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvoiceServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.InvoiceService.IInvoiceService>, KeithLink.Svc.WebApi.com.benekeith.InvoiceService.IInvoiceService {
        
        public InvoiceServiceClient() {
        }
        
        public InvoiceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvoiceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvoiceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KeithLink.Svc.Core.Models.Invoices.InvoiceModel[] ReadInvoices(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo) {
            return base.Channel.ReadInvoices(user, catalogInfo);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceModel[]> ReadInvoicesAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo) {
            return base.Channel.ReadInvoicesAsync(user, catalogInfo);
        }
        
        public KeithLink.Svc.Core.Models.Invoices.InvoiceModel ReadInvoice(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, long Id) {
            return base.Channel.ReadInvoice(user, catalogInfo, Id);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.InvoiceModel> ReadInvoiceAsync(KeithLink.Svc.Core.Models.Profile.UserProfile user, KeithLink.Svc.Core.Models.SiteCatalog.UserSelectedContext catalogInfo, long Id) {
            return base.Channel.ReadInvoiceAsync(user, catalogInfo, Id);
        }
        
        public KeithLink.Svc.Core.Models.Invoices.TermModel ReadTermInformation(string branchId, string termCode) {
            return base.Channel.ReadTermInformation(branchId, termCode);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Invoices.TermModel> ReadTermInformationAsync(string branchId, string termCode) {
            return base.Channel.ReadTermInformationAsync(branchId, termCode);
        }
    }
}
