// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class adduserpushnotificationdevice20141119 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduserpushnotificationdevice20141119));
        
        string IMigrationMetadata.Id
        {
            get { return "201411200343175_add user push notification device 20141119"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
