// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20150430_AddDSRAliases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150430_AddDSRAliases));
        
        string IMigrationMetadata.Id
        {
            get { return "201504301620237_20150430_Add DSR Aliases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
