// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _201502032124119_20150203_change_route_number_maxlength_to_four : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201502032124119_20150203_change_route_number_maxlength_to_four));
        
        string IMigrationMetadata.Id
        {
            get { return "201502041735040_201502032124119_20150203_change_route_number_maxlength_to_four"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
