// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class increase_order_history_invoice_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(increase_order_history_invoice_length));
        
        string IMigrationMetadata.Id
        {
            get { return "201504031553440_increase_order_history_invoice_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
