// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddSpecialOrderFlagtoOrderHistoryHeader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSpecialOrderFlagtoOrderHistoryHeader));
        
        string IMigrationMetadata.Id
        {
            get { return "201602042227402_Add Special Order Flag to Order History Header"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
