//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.ContentManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.ContentManagementService.IContentManagementService")]
    public interface IContentManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/CreateContentItem", ReplyAction="http://tempuri.org/IContentManagementService/CreateContentItemResponse")]
        void CreateContentItem(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/CreateContentItem", ReplyAction="http://tempuri.org/IContentManagementService/CreateContentItemResponse")]
        System.Threading.Tasks.Task CreateContentItemAsync(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/ReadActiveContentItemsByBranch", ReplyAction="http://tempuri.org/IContentManagementService/ReadActiveContentItemsByBranchRespon" +
            "se")]
        KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[] ReadActiveContentItemsByBranch(string branchId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/ReadActiveContentItemsByBranch", ReplyAction="http://tempuri.org/IContentManagementService/ReadActiveContentItemsByBranchRespon" +
            "se")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[]> ReadActiveContentItemsByBranchAsync(string branchId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/ReadContentItemsByBranch", ReplyAction="http://tempuri.org/IContentManagementService/ReadContentItemsByBranchResponse")]
        KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[] ReadContentItemsByBranch(string branchId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/ReadContentItemsByBranch", ReplyAction="http://tempuri.org/IContentManagementService/ReadContentItemsByBranchResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[]> ReadContentItemsByBranchAsync(string branchId, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/DeleteContentItemById", ReplyAction="http://tempuri.org/IContentManagementService/DeleteContentItemByIdResponse")]
        void DeleteContentItemById(int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/DeleteContentItemById", ReplyAction="http://tempuri.org/IContentManagementService/DeleteContentItemByIdResponse")]
        System.Threading.Tasks.Task DeleteContentItemByIdAsync(int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/ReadContentItemById", ReplyAction="http://tempuri.org/IContentManagementService/ReadContentItemByIdResponse")]
        KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel ReadContentItemById(int itemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/ReadContentItemById", ReplyAction="http://tempuri.org/IContentManagementService/ReadContentItemByIdResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel> ReadContentItemByIdAsync(int itemId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContentManagementServiceChannel : KeithLink.Svc.WebApi.com.benekeith.ContentManagementService.IContentManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentManagementServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.ContentManagementService.IContentManagementService>, KeithLink.Svc.WebApi.com.benekeith.ContentManagementService.IContentManagementService {
        
        public ContentManagementServiceClient() {
        }
        
        public ContentManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateContentItem(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem) {
            base.Channel.CreateContentItem(contentItem);
        }
        
        public System.Threading.Tasks.Task CreateContentItemAsync(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem) {
            return base.Channel.CreateContentItemAsync(contentItem);
        }
        
        public KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[] ReadActiveContentItemsByBranch(string branchId, int count) {
            return base.Channel.ReadActiveContentItemsByBranch(branchId, count);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[]> ReadActiveContentItemsByBranchAsync(string branchId, int count) {
            return base.Channel.ReadActiveContentItemsByBranchAsync(branchId, count);
        }
        
        public KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[] ReadContentItemsByBranch(string branchId, int count) {
            return base.Channel.ReadContentItemsByBranch(branchId, count);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel[]> ReadContentItemsByBranchAsync(string branchId, int count) {
            return base.Channel.ReadContentItemsByBranchAsync(branchId, count);
        }
        
        public void DeleteContentItemById(int itemId) {
            base.Channel.DeleteContentItemById(itemId);
        }
        
        public System.Threading.Tasks.Task DeleteContentItemByIdAsync(int itemId) {
            return base.Channel.DeleteContentItemByIdAsync(itemId);
        }
        
        public KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel ReadContentItemById(int itemId) {
            return base.Channel.ReadContentItemById(itemId);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.ContentManagement.ContentItemViewModel> ReadContentItemByIdAsync(int itemId) {
            return base.Channel.ReadContentItemByIdAsync(itemId);
        }
    }
}
