//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.ContentManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.ContentManagementService.IContentManagementService")]
    public interface IContentManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/CreateContentItem", ReplyAction="http://tempuri.org/IContentManagementService/CreateContentItemResponse")]
        void CreateContentItem(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContentManagementService/CreateContentItem", ReplyAction="http://tempuri.org/IContentManagementService/CreateContentItemResponse")]
        System.Threading.Tasks.Task CreateContentItemAsync(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContentManagementServiceChannel : KeithLink.Svc.WebApi.com.benekeith.ContentManagementService.IContentManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentManagementServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.ContentManagementService.IContentManagementService>, KeithLink.Svc.WebApi.com.benekeith.ContentManagementService.IContentManagementService {
        
        public ContentManagementServiceClient() {
        }
        
        public ContentManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateContentItem(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem) {
            base.Channel.CreateContentItem(contentItem);
        }
        
        public System.Threading.Tasks.Task CreateContentItemAsync(KeithLink.Svc.Core.Models.ContentManagement.ContentItemPostModel contentItem) {
            return base.Channel.CreateContentItemAsync(contentItem);
        }
    }
}
