//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeithLink.Svc.WebApi.com.benekeith.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="com.benekeith.ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetItemUsageForCustomer", ReplyAction="http://tempuri.org/IReportService/GetItemUsageForCustomerResponse")]
        KeithLink.Svc.Core.Models.Reports.ItemUsageReportItemModel[] GetItemUsageForCustomer(KeithLink.Svc.Core.Models.Reports.ItemUsageReportQueryModel usageQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetItemUsageForCustomer", ReplyAction="http://tempuri.org/IReportService/GetItemUsageForCustomerResponse")]
        System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Reports.ItemUsageReportItemModel[]> GetItemUsageForCustomerAsync(KeithLink.Svc.Core.Models.Reports.ItemUsageReportQueryModel usageQuery);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : KeithLink.Svc.WebApi.com.benekeith.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<KeithLink.Svc.WebApi.com.benekeith.ReportService.IReportService>, KeithLink.Svc.WebApi.com.benekeith.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KeithLink.Svc.Core.Models.Reports.ItemUsageReportItemModel[] GetItemUsageForCustomer(KeithLink.Svc.Core.Models.Reports.ItemUsageReportQueryModel usageQuery) {
            return base.Channel.GetItemUsageForCustomer(usageQuery);
        }
        
        public System.Threading.Tasks.Task<KeithLink.Svc.Core.Models.Reports.ItemUsageReportItemModel[]> GetItemUsageForCustomerAsync(KeithLink.Svc.Core.Models.Reports.ItemUsageReportQueryModel usageQuery) {
            return base.Channel.GetItemUsageForCustomerAsync(usageQuery);
        }
    }
}
