// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OrderHistory_rev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderHistory_rev1));
        
        string IMigrationMetadata.Id
        {
            get { return "201410241416476_OrderHistory_rev1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
