// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Merge_EF_Models_JT_20141030 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Merge_EF_Models_JT_20141030));
        
        string IMigrationMetadata.Id
        {
            get { return "201410302145006_Merge_EF_Models_JT_20141030"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
