// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Messaging_v1_20142204 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Messaging_v1_20142204));
        
        string IMigrationMetadata.Id
        {
            get { return "201411041805302_Messaging_v1_20142204"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
