// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Modifications_to_ItemHistory_add_unitofmeasure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modifications_to_ItemHistory_add_unitofmeasure));
        
        string IMigrationMetadata.Id
        {
            get { return "201506081437143_Modifications_to_ItemHistory_add_unitofmeasure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
