// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class emptyMigrationForMerge__v1_2__with__v1_3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emptyMigrationForMerge__v1_2__with__v1_3));
        
        string IMigrationMetadata.Id
        {
            get { return "201508181925151_emptyMigrationForMerge__v1_2__with__v1_3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
