// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _20151023addingexternalcatalog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20151023addingexternalcatalog));
        
        string IMigrationMetadata.Id
        {
            get { return "201510231909196_2015-10-23-adding-external-catalog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
