// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addorderdeliveryinfofieldstoorderhistoryheader : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addorderdeliveryinfofieldstoorderhistoryheader));
        
        string IMigrationMetadata.Id
        {
            get { return "201501142314465_add order delivery info fields to order history header"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
