// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Added_CustomerName_Branch_To_UserMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_CustomerName_Branch_To_UserMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131809528_Added_CustomerName_Branch_To_UserMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
