// <auto-generated />
namespace KeithLink.Svc.Impl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class removecontentitemstableafter1_5merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecontentitemstableafter1_5merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201603162117290_remove content items table after 1_5 merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
