CREATE NONCLUSTERED INDEX [IX_ContractDetails_HeaderId] ON [List].[ContractDetails]
(
	[HeaderId] ASC,
	[ItemNumber] ASC,
	[Each] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


